### ISSUE TITLE
Ideas card- Widget like count- wrong work count when click at first on like and after ckick on dislike

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#10]
Steps of reproduce
1. Log in
2. go to https://beta.utradea.com/positions/601af701fdb1db6a59d9a486
3. Click like (the idea has 1 like) (1 like + 1 like == 2)
4. Click dislike (2-1==1)

**Actual result:**  Position has 0 likes
**Expected result:** Position has 1 likes

**Comment by zhan1634** [comment]
This is not a bug. Once you switch from like to dislike, you change from +1 to -1. The idea originally has 1 like. You click thumbs up (2 likes), you click thumbs down (0 likes). Please explain your reasoning more clearly.

**Comment by nonameuser2019** [comment]
counter of likes is gone, this is not a bug more
