### ISSUE TITLE
Getting multiple mails for the support ticket.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#100]
STR:
1. Login with valid creds.
2. Click on setting
3. Click on Update profile settings.
4. Scroll down till contact support.
5. Select any option
6. Enter details in the box.
7. Click on submit button multiple times.
8. Now check the mail.

Expected: Should only get one email.

Actual : Getting multiple mail.

Refer Screencast: http://somup.com/crehhBDNhe

**Comment by zhan1634** [comment]
Fixed in the latest version.
