### ISSUE TITLE
Getting no validation for blank support ticket description field.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#101]
STR:

1. Login with valid creds.
2. Click on setting
3. Click on Update profile settings.
4. Scroll down till contact support.
5. Select any option
6. Leave description box blank
7. Click on submit button.
8. Observe the behavior

Refer Screencast: http://somup.com/crehhHDNhB

**Comment by zhan1634** [comment]
There really doesn't need to be a validation - there's nothing, so when you submit nothing happens.
