### ISSUE TITLE
Validation is getting overlapped and visible after open the same page in new tab.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#102]
STR:
1. Login with valid creds.
2. Click on Post an Idea.
3. Fill all the details step by step.
4. For the title field skip it and click next.
5. Validation will appear.
6. Select that validation and copy it.
7. Click on preview button "Click to preview your idea in new tab".
8. Observe the footer of the new tab.

Screencast: http://somup.com/crehQiDNqs

**Comment by zhan1634** [comment]
I cannot replicate this error.
