### ISSUE TITLE
Duplicacy of User Ideas are seen in Post an idea tab.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#103]
There is no such steps, which could describe this issue. I just created a new user and I have seen that and when I saved one and it shown for both ideas. Only I can say, you need to investigate on this issue.

Refer Screencast: http://somup.com/cre1QLDPD0

**Comment by zhan1634** [comment]
This is not a duplicate, if you look at the top, one is the OPEN of an idea, the other is the CLOSE of an idea. We are working later this week to make it more clear

**Comment by zhan1634** [comment]
Resolved with new update
