### ISSUE TITLE
Count of letters are not increasing until we click on it.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#105]
1. Login with valid creds.
2. Click on Post an idea.
3. Select ticker.
4. Move to next and write down your idea in box.
5. Observe the letters count are getting increased or not.

Screencast: http://somup.com/cre16uDPb3

**Comment by zhan1634** [comment]
This is fine, there's just a delay in the processing time because we leveraging a widget to help with the processinging. This delay I cannot fix.
