### ISSUE TITLE
Getting log out when user check there idea by clicking on preview to check your idea button.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#106]
STR:
1. Login with valid creds.
2. Click on Post an idea.
3. Fill all the details.
4. On the last click on preview to check your idea in new tab button.
5. Observe the result.

Expected: It should not log out and stay logged in.

Actual: Getting logged out.

Screencast: http://somup.com/cre16EDPbH

**Comment by Ashish8822** [comment]
@zhan1634 
1. Does selecting catalyst and time frame are mandatory or we can skip them?
2. Does the user should have an option to edit their ideas after posting or not? 
3. While posting an ideas the target price what we choose the same should display under target section of active ideas or different. Could you brief that how target price would work?

**Comment by zhan1634** [comment]
1. Catalyst is optional, timeframe is mandatory. 
2. Not allowed to edit after. 
3. It'll be more clear in the next iteration coming out later this week.

**Comment by zhan1634** [comment]
The logout is the same as the saved function, there's something that's happening with the lag. Your network is slower, so I need to debug what the difference in network speed is causing.
