### ISSUE TITLE
Without selecting time frame for an idea it is showing by default.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#107]
STR:
1. Login with valid creds.
2. Click on post an idea.
3. Fill the details.
4. Skip time frame.
5. Click on submit after all the details filled.
6. Observe the time frame.

Screencast: http://somup.com/cre168DPFl

**Comment by zhan1634** [comment]
Timeframe is default set to <1 week. A timeframe must be selected. This default was not reflected in the position upload. This will be updated in the latest release to beta and production tonight.
