### ISSUE TITLE
SEC DataService Working - Investigating 

### ISSUE THREAD

**Issue by TaiPanda96** [Utradea-Inc/utradea-public#108]
Routine Code Review Determined there was an issue with SEC Data Service Feed.

The output logs are not printing and it appears the process is being hung.

Investigating:

PROD LOG
DEV LOG
DEV NEW SEC LOG
DEV NEW SEC FORM 4 LOG

Going to be checking:

Connectivity to MongoDB (doesn't seem to be the issue)
Checking IP 

Checking if any Webservice for SEC8K, LATESTFILINGS, SECFORM4 is breaking.

Will provide update with screenshots.

**Comment by zhan1634** [comment]
What's the update on this?

**Comment by TaiPanda96** [comment]
Logs are working now. However, doing another code review on the SEC this morning and found a few issues. Fixing atm.
Item Headers (Item 1.01) is not updating into database as expected. Working on fixing.
