### ISSUE TITLE
Invalid Colour of Validation in Update profile section in mobile version

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#109]
Steps to reproduce :
1. Go to www.m.beta.utradea.com
2. Login to your account
3. Click on more and go to setting
4. Leave the first name blank and click on submit
5. Observe the result
 Note : The color of validation is green with a tick mark . It should be red with a ! mark . Working fine in desktop version

Screen recording : https://screencast-o-matic.com/watch/cre6hmVcYGZ

**Comment by zhan1634** [comment]
Can we discuss this? I cannot recreate this error.
