### ISSUE TITLE
Profile setting- Wrong visible tool tip before hover on icons

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#11]
Windows 10 Chrome

Steps of reproduce
1.go to https://beta.utradea.com/session/signup
2. Click on Settings Icon in left sidebar
3. Hover mouse cursore on icon of settings

**Actual result:** The tooltip is blocked another element (all three icons in that block isn't visible)
**Expected result:** The tooltip is visible
screen: https://prnt.sc/z4774t

**Comment by zhan1634** [comment]
Resolved in update V3.7: Release - February 15th at 11:59 PM EST.

**Comment by nonameuser2019** [comment]
fixed
