### ISSUE TITLE
Word coming out from highlighter box in notification

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#111]
Steps to reproduce : 
1. Go to https://beta.utradea.com
2. Login to your account
3. Click on notification and hover your mouse over any notification
4. Observe the highlighted box

Screen recording : https://share.vidyard.com/watch/jfKQ2t2KErE3T1nyY9ue92?

Note: In the video above you can easily see when user hover their mouse to the notification a highlighted box appear . The last work "R" is coming out from highlighted box .

Tested on chrome, edge, Firefox

**Comment by zhan1634** [comment]
Although this is is a visual bug, there's nothing that can be done about it without causing larger UI problems. Realistically, no SINGLE word will be that long so this will not show up in production unless someone puts an absurd title.

**Comment by Ashish8822** [comment]
> Although this is is a visual bug, there's nothing that can be done about it without causing larger UI problems. Realistically, no SINGLE word will be that long so this will not show up in production unless someone puts an absurd title.

According to the business requirement it is allowed to add 100 words in the title ? So what's the point of allowing 100 words then ? Should I try to type a title which have a sentence of different words ?

**Comment by zhan1634** [comment]
I'm surprised you're still awake - if so at 11:00AM EST I'm updating Google Login if you can check that. 

Okay. for this bug, yes you are correct 100 character limit, however - most titles will be "TSLA is going to the moon" - there are natural space breaks between the words. I'm saying there are very little cases where there is one word ... emphasis on the ONE word that will be over 30-40 characters. Now if they do spam or put "@@@@@@@@@@@@@@" that will be a case, but it's rare. Does that make sense?
