### ISSUE TITLE
Only half content is showing in reset page

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#112]
Steps to reproduce :

1.Go to https://beta.utradea.com
2. Click on reset password
You will see only half content on the right side of window  . 

Screen recording : https://share.vidyard.com/watch/UTW4ohUu57yxbTq98jTVJV?
Note : Tested on Chrome Firefox and Edge. Clear Cache and Cookies data.

**Comment by zhan1634** [comment]
Updated in the next beta push

**Comment by Ashish8822** [comment]
@zhan1634 Is there any another way to communicate other than GitHub so that things gets clear in better way ????

**Comment by zhan1634** [comment]
send an email to support@utradea.com - > download discord

**Comment by Ashish8822** [comment]
> send an email to [support@utradea.com](mailto:support@utradea.com) - > download discord

Please add me to discord . My id is ashish#7488. I am unable to add you .
