### ISSUE TITLE
Submit button is disabled still reset password is request is being send while pressing enter button 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#117]
Steps :
1. Go to https://beta.utradea.com/
2. Click on Reset password
3. Enter email -id you want to reset password for 
4. Click on submit button
5. Success message will popup and submit button will disappear
6. Again press enter and see that again a request for reset password has been sent 

Screen recording : https://share.vidyard.com/watch/NHtMkst87KU4xqY9PTNCnf?

**Comment by zhan1634** [comment]
Disabled after key enter.
