### ISSUE TITLE
Update Profile- The element of Contact Support isn't clicable

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#12]
**Step to reproduce:**
1.go to https://beta.utradea.com/session/signup
2. Click on Settings Icon in left sidebar
3. Click on Settings

**Actual result:** The element of Contact Support isn't clicable
**Expected result:** The element of Contact Suport is clicable

screen https://prnt.sc/z47m3b

**Comment by zhan1634** [comment]
Hm... it works sometimes, and other times it doesn't. Not sure why this is the case.

**Comment by zhan1634** [comment]
This should be resolved in update V3.7: Release - February 15th at 11:59 PM EST.
