### ISSUE TITLE
Unable to login with google.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#120]
STR:
1. Hit the URL.
2. Click on the "Login with google"
3. Fill the credentials
4. And click on sign in.
5. And observe the result.

Note:
After following the above steps you will be blocked to login with google.

Screencast: http://somup.com/crelQ9b1Pj

**Comment by leiron-james** [comment]
Issue with Android app as well.

Error after clicking sign in from Google:

**Comment by zhan1634** [comment]
App doesn't work - desktop incognito does not work
