### ISSUE TITLE
Like unlike button under the ideas section appears to be too large in size

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#121]
Steps to Reproduce:
1.Go to https://beta.utradea.com/
2. Login with your credentials
3. Go to portfolio tab and under ideas section open any active idea
4. Observe

Screen recording : https://share.vidyard.com/watch/4YSPjnjG6ZwzMS1yokNiZr?
Note: Tested on Chrome, Firefox, Edge

**Comment by zhan1634** [comment]
Oops.
