### ISSUE TITLE
Profile tab button not working when clicked on notification tab

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#122]
Steps to reproduce : 
1. Go to https://beta.utradea.com/
2. Login with your credentials
3. Click on notification tab and then click on profile tab 
4. Observe the result

Note : When you click on notification tab and then click on investment tab , The notification tab automatically gets closed . But when you click on notification tab and then click on profile tab nothing happens. Accordingly notification tab should get closed and profile tab should appear.

Screen Recording : https://share.vidyard.com/watch/6fCFW9qEVBXGVLmhjTd56H?

**Comment by zhan1634** [comment]
So, although this is a bug.. it's not really. The settings is a popup, and you currently already have a pop-up open, so yes we can optimize for that and have it pop-up there. Not a significant update / UX change. Not worth the effort atm.

The second thing - you are ALREADY on the feed, so it doesn't go to a new page.
