### ISSUE TITLE
Post an idea section allowing to navigate to next page when we have already 10 ideas 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#123]
Note : Before performing the below steps make sure you have already 10 ideas in your portfolio .
Steps:
1.Go to https://beta.utradea.com/
2. Click on post an idea section
3. Select a ticker
4. Click on next button ( It will throw message saying you already have 10 ideas)
5. Now again select some other ticker and overwrite it
6. Click next
7. Observe
Screen recording : https://share.vidyard.com/watch/gVwBrdr7n5CYTxH6XKtu8q?

**Comment by zhan1634** [comment]
updated in next release
