### ISSUE TITLE
Hyperlink should be open up in new tab 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#124]
Steps to reproduce :
1. Go to https://beta.utradea.com/
2. Click on portfolio 
3. Navigate over any idea which have hyperlink in it
4. Click on hyperlink
5. Observe

Screen recording : https://share.vidyard.com/watch/Hr8YKUL2Ff36YP4GXzvNSr?

**Comment by zhan1634** [comment]
resolved in next update
