### ISSUE TITLE
Click to preview before posting idea not working in firefox 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#125]
Steps to reproduce
1. Open Firefox
2. go to https://beta.utradea.com/
3. click on post an idea section and select ticker, write your idea & select time frame
4. Before submitting click on preview idea .
5. Observe
Screen recording :  https://share.vidyard.com/watch/FGoHJ2dTYMStz8BMD1pjCL?
Note : Working fine in chrome

**Comment by zhan1634** [comment]
This works for me, I cannot replicate.
