### ISSUE TITLE
Priority 5: status bar blocks top + grey block bottom of screen

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#127]
![Screenshot_20210329-223640_Expo Go](https://user-images.githubusercontent.com/14366944/112925815-78e0bb00-90e0-11eb-957f-4cee51d74370.jpg)

Cannot click back button, notifications, search

Grey area bottom half of screen

**Comment by zhan1634** [comment]
this should be resolved in the latest version
