### ISSUE TITLE
When user use logout and log in leter he comes the same page.

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#13]
Steps of reproduce
1.go to https://beta.utradea.com/session/signup
2. Click on Settings Icon in left sidebar
3. Click on Settings
4. Click on icon to go to profile
5. Click logout button
6. Log in to vebsite
**Actual result:** User log in to user profile page
**Expected result:**  User log in to main page

**Comment by zhan1634** [comment]
This happens because the session is maintained. If you close the tab and log in this doesn't happen. It is rare that a user will log out and log back in without closing the browser - (unless there's a specific scenario in mind).

**Comment by nonameuser2019** [comment]
ok
