### ISSUE TITLE
Priority 1: When you tab between the timelines for graph, it flashes white before it updates

### ISSUE THREAD

**Issue by vlynchn** [Utradea-Inc/utradea-public#131]

**Comment by zhan1634** [comment]
DIS IS MAKING ME MAD. I KNOW WHATS HAPPENING AND I CAN'T GET RID OF IT.

**Comment by vlynchn** [comment]
> DIS IS MAKING ME MAD. I KNOW WHATS HAPPENING AND I CAN'T GET RID OF IT.

Did you figure it out? LOL

**Comment by zhan1634** [comment]
no

**Comment by zhan1634** [comment]
UPDATED.
