### ISSUE TITLE
Resise browser window- When user try resize browser much twiching

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#14]
**Steps of reproduce**
1.go to https://beta.utradea.com/session/signup
2. Click to resize browser window

**Actual result:** The window behavior incorrect(to watch a video)
**Expected result:**  Resize window

https://drive.google.com/file/d/1elA-OMyb2ecd2l7A2IFRnLe2F_n7xBGT/view?usp=sharing

**Comment by zhan1634** [comment]
Duplicate bug number #55

**Comment by nonameuser2019** [comment]
Duplicate is a bug #55 
Look at  date of creation
