### ISSUE TITLE
Priority 3: two issues in this screenshot

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#147]
![Screenshot_20210330-183451_Expo Go.jpg](https://user-images.githubusercontent.com/14366944/113192732-23fe8b00-922d-11eb-9757-fc4b69b355fa.jpg)

1. Increase font size of daily change and ticker name for better readability

2. The "closed" cards' background images are still coloured

**Comment by graceeguo** [comment]
Ticker name size issue also on news cards

**Comment by zhan1634** [comment]
Lets discuss about the overlay.
