### ISSUE TITLE
Portfolio page- Wrong data in Top Sectors and Top Industries blocks

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#15]
**screen** https://prnt.sc/z4k5jv	

**Steps of reproduce**
1.go to https://beta.utradea.com/session/signup
2. Create new user
3. Click to portfolio
4. Click on Ideas Tab

**Actual result:** The widget top sectors and top industries has NAN value
**Expected result:**  The widget can has 0 value or other correct value

**Comment by zhan1634** [comment]
Resolved in update V3.7: Release - February 15th at 11:59 PM EST.

**Comment by nonameuser2019** [comment]
fixed
