### ISSUE TITLE
Portfolio page- Doesn't resing content blocks with resizing browser window

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#16]
**screen:** https://prnt.sc/z4neux	

**Steps of reproduce** 
1.go to https://beta.utradea.com/session/signup
2. Create new user
3. Move to porfolio
4. resize browser to size that with browser will be 1200 or less

**Actual result:** Content in left column is not resizing
**Expected result:** Content resizing

**Comment by zhan1634** [comment]
This will be part of a larger update. For the purposes of this release, we are okay with this "bug."

**Comment by nonameuser2019** [comment]
Not fixed
