### ISSUE TITLE
Create idea step 6- Possibility to click button TO NEXT witn empty field of Quick Intro

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#17]
**Steps of reproduce**
1.go to https://beta.utradea.com/session/signup
2. Log in to accoumt
3. Click on Post an Idea
4. Create new idea, pass all steps to step 6
5. With Empty Quick Intro click to next button
6. 
**Actual result:** Move to step 7
**Expected result:** The button is not clicable with empty field

**Comment by zhan1634** [comment]
Resolved in update V3.7: Release - February 15th at 11:59 PM EST.

**Comment by nonameuser2019** [comment]
fixed
