### ISSUE TITLE
Priority 1:  Industry and Sector not correct for stock post (From user TedInvests)

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#174]
![image](https://user-images.githubusercontent.com/74615189/113795497-0d6b9e80-971b-11eb-849a-56dcd6e81551.png)

Should be:

Sector(s): Consumer Defensive
Industry: Packaged Foods

https://utradea.com/positions/606cf13bfd9fb80bd3d39781

**Comment by zhan1634** [comment]
the algorithm classified this company's food as cat and dog food whatcha gonna do
in all seriousness I can't control this, this is straight from our data feeds
