### ISSUE TITLE
data under ideas keeps on changing

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#176]
Steps 
1. Go to www.beta.utradea.com
2. Go to portfolio page
3. Click on ideas
4. In the top sector see the last point and its data 
5. Now again click on watchlist and then again on idea 
6. You will see that the last point data has been changed 

Screen recording: https://share.vidyard.com/watch/M3q6LW7PQV5Qvjuyp471wa?

**Comment by zhan1634** [comment]
not a bug, there's 2 records with 11% so it'll switch it out.
