### ISSUE TITLE
Invalid validation colour and character limit on email in mobile app

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#177]
When updating email id i have a working email id ashish.labh1603@yopmail.com it throws error that maximum limit reach . 
Also first time it throws error in red colour second time it throws error in green colour .

Character limit issue on Webpage also 
Screen recording : https://screencast-o-matic.com/watch/crfiItVnQy5

**Comment by zhan1634** [comment]
resolved in next update
