### ISSUE TITLE
Issue in the profile tab

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#18]
**Steps of reproduce**
1.go to https://beta.utradea.com
2. Log in to account
3. Navigate to Profile
4. In profile section hover your mouse over setting , logout , and invite icon
5. There name should be displayed above not behind the box . 
Actual result: Name should be appeared on the box 
Expected result: No Display of names as its behind the box.

Video 
http://somup.com/crno3xDqqx

**Comment by zhan1634** [comment]
Resolved in update V3.7: Release - February 15th at 11:59 PM EST.
