### ISSUE TITLE
Invalid color of bullish stock in mobile application

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#185]
Steps:
Login >> Portfolio tab>> Ideas >> in the idea section it is denoted that red color is for bearish  , green for bull and grey for donot track. Ideas which are bullish in nature shows green return value and idea which is bearish in nature is also showing green . But when you login with website and check for the same idea it is showing red in website and green in mobile application. 

Screen recording : https://screencast-o-matic.com/watch/crfX2TVnZnF  
Screenshot : https://share.getcloudapp.com/eDujBKQ4  (Please check the dot colour in return value for random test on 8th april idea and compare with same idea on mobile application from screen recording above.

**Comment by zhan1634** [comment]
this one is going to be a bigger update - will update the new UI tomorrow
