### ISSUE TITLE
In tutorial stock search option is not adding watchlist in portfolio in mobile application

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#186]
When register as a new user tutorial comes up it ask to search stocks and then it add it to portfolio under your watchlist section in website . But for the same in mobile application it is not adding in watchlist . watchlist still showing zero

screen recording : https://screencast-o-matic.com/watch/crfXIMVn0Wu

**Comment by zhan1634** [comment]
same as previous bug, updated in the next release
