### ISSUE TITLE
When we click on edit button the items in top sector changes .

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#19]
Steps of reproduce
1.go to https://beta.utradea.com
2. Log in to account
3. Click on portfolio tab
4. Navigate to watchlist section 
5. Go to the edit button and click on it
6.Observe the items in top sector box 
Actual result: Item is not static its moving up and down while clicking on edit button
Expected result: The items under top sector should be static

Video
http://somup.com/crno3BDqYI

**Comment by zhan1634** [comment]
Resolved in update V3.7.2: Release - February 17th at 11:59 PM EST.
