### ISSUE TITLE
Like unlike button not stable 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#20]
Steps of reproduce
1.go to https://beta.utradea.com
2. Log in to account
3. Click on investment tab
4. Navigate to Alex Qa idea
5. Then click on like and unlike button
6.Observe that when you click on like button once it will increase by 2 value and when you press unlike button once it will decrease by 2 values
Actual result: when you click on like button once it will increase by 2 value and when you press unlike button once it will decrease by 2 values
Expected result: It should increase by 1 value 

Video
http://somup.com/crnDQtDYht

**Comment by zhan1634** [comment]
The like button is stable, this is how the likes work. If you change from like to dislike -> you remove your like (-1) and add a Dislike (-1) which is equal to (-2).
