### ISSUE TITLE
Observation in notification for verify email address popup

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#204]
1. As user login for first time he was asked to verify his email account and as he click on that verification button , no message pop up that email link has been send and the blue border remain there without any message on it
2. Now user do hard refresh ctrl+shift+r  again the send verification email message popped up
3. Now this time user click on send verification mail button he gets the message email sent .

Screen recording: https://share.vidyard.com/watch/AvuwqTZtG2m2BwUyPF3xzj?

**Comment by zhan1634** [comment]
fixed
