### ISSUE TITLE
Data is getting fetched from earlier posted idea to the new ticker.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#21]
Steps 
1. Click on "Post an idea" 
2. Search ticker and select from dropdown.
3. Go to choose your analysis.
4. Select any one from above steps.
5. Now post an idea and move to next.
6. Choose any three catalyst.
7. Click on Next
8. Select time frame and confidence.
9. Click on Next and enter quick intro.
10. Now repeat from steps 2 to 9 .
11. Observe the result.
Actual Result: Data is getting fetched from earlier posted idea to the new ticker
Expected Result: It should not fetch data from earlier posted ideas

Video:
http://somup.com/crnD6FDY6D

**Comment by zhan1634** [comment]
This has been resolved and deployed to beta as of Feb 24, 2020 11:59PM EST.
