### ISSUE TITLE
Inconsistencies in Profile Picture Quality and Sizing on Mobile App 

### ISSUE THREAD

**Issue by vicxnguyen** [Utradea-Inc/utradea-public#218]
See attached images. Uploaded pictures, template icons, and letter icons all show up as different sizes and thus have different distances from the text column. 

![IMG_4768](https://user-images.githubusercontent.com/50087329/116168782-3c997e00-a6d1-11eb-9571-b81f28857d5b.PNG)
![IMG_4769](https://user-images.githubusercontent.com/50087329/116168783-3c997e00-a6d1-11eb-9246-7cb8c18da3e1.PNG)
![IMG_4770](https://user-images.githubusercontent.com/50087329/116168785-3d321480-a6d1-11eb-806c-ec2b7d23a6c9.PNG)

**Comment by zhan1634** [comment]
Fixed in next release
