### ISSUE TITLE
price change/fluctuated rate and percentage is not correctly calculated.

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#219]
https://drive.google.com/file/d/1jLUz19l2_xxe1OrBzykbjABVLn0kdP_J/view?usp=sharing
In the attached video URL You can find that:

Actual Result:
On April 12, The price = 701.98
On April 13, The price = 762.32 , Rise = 49.62 (6.96%)
On April 14, The price = 732.23 , price fall = -38.47 (4.99%)

Expected Result:
On April 13, The price = 762.32 , Rise = 60.34 (8.60%)
On April 14, The price = 732.23 , price fall = -30.09 (3.94%)

**Comment by zhan1634** [comment]
Okay so this is a bit interesting, this is not the price change from one day to the next, this is the change during the day and the price you see is the closing market price.

**Comment by raqeshmandhan** [comment]
Okay, so that's not a bug,  do I have to close the issue now?
