### ISSUE TITLE
Overlap issue. (you will see overlap border when you select name email from auto select option )

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#22]
**Steps to reproduce**
1. Go to https://beta.utradea.com
2. Log in to account
3. Click on Profile tab
4. Navigate over settings
5. In update profile enter First name , Last name , Email id , Username while using auto select.

Expected result: User should not be able to see overlap border
Actual result:  Box is overlapped
Video : http://somup.com/crnDX2DY27
Screenshot : https://screencast-o-matic.com/i/crnDXbSgiX
Note: Only in chrome , working fine in Firefox and Edge.

**Comment by zhan1634** [comment]
This is a chrome issue. Cannot resolve due to the nature of google chrome. May need to rethink autofill in the future.
