### ISSUE TITLE
In 3M Graph, the days are not complete.

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#220]
Steps to Reproduce:
Utradea home page > click on "POOOOORRRN DICKS SHIT FUCK" > Click on "jokinglol" > Active Watchlist > GBAB

- For the first time, in the 3M line bar graph. Last day would be random and you would see 3 months won't be complete.
- Video URL: https://www.youtube.com/watch?v=0IyZqLBu_WI

**Comment by zhan1634** [comment]
I don't get what you mean with this bug

**Comment by zhan1634** [comment]
This will defined more clearly.

**Comment by raqeshmandhan** [comment]
Okay, so for this, as you can find this in the attached video:

- Initially, the graph is loaded with the 3 months data, from 28th January to 15th April. (it needed to be present till 26th April)
- I click the 6M for loading 6 months data, here the data was available till the 26th of April.
- I clicked again 3M for loading 3 months data, the data was updated till the 26th of April.


**Issue:** In the graph, The data must be updated till the last day when we load the page.
