### ISSUE TITLE
Unable to use chat (High)

### ISSUE THREAD

**Issue by LilkitFutDev** [Utradea-Inc/utradea-public#225]
**Area Path:** | https://beta.utradea.com/ 

**Severity:** | High 

**Reported By:** | Yarov 

**Description:** | The chat with the user does not start after   searching for the user in the messenger 

**Steps To Reproduce:**
1 | Go to https://beta.utradea.com/
2 | Click on the "messenger" button 
3 | Enter in the "search" field username 
4 | Click on the username
5 | Pay attention to the main screen 

**Expected Result:** | A window appears with the user's chat
**Actual result:** | The chat with the user does not start after   searching for the user in the messenger

**Attachment:** | https://www.dropbox.com/s/acxykwqch2labxb/bandicam%202021-04-28%2012-19-09-644.mp4?dl=0

**Comment by LilkitFutDev** [comment]
**Most likely this is due to the long loading of the messenger** 

**I also figured out that the messenger starts working after the page is reloaded**
Attachment: | https://www.dropbox.com/s/q2lketdfsbl8csn/bandicam%202021-04-29%2013-46-29-415.mp4?dl=0

**Comment by zhan1634** [comment]
Messenger will be updated in the next release. It has been pulled from this release.
