### ISSUE TITLE
User's Image does not appear in Messenger

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#226]
Steps to verify/reproduce:
1. Go to the user profile/portfolio whose Image is available.
2. Click on the message icon to send the text.
3. The chatbox will open in messenger. 

**Issue:** you will find an image icon that would appear with the first letter of the user (e.g. "R" ), but the Image would not be displayed.

Video URL: [https://youtu.be/fZ3LAkYz0Cc](https://youtu.be/fZ3LAkYz0Cc)

**Comment by zhan1634** [comment]
try updating it now, it should be fixed.
