### ISSUE TITLE
User's Chat box must be opened in messenger when clicking on message button/Icon from user's portfolio

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#237]
Steps to reproduce: 
Go to User portfolio > Click Message Icon 

Issue: User doesn't appear in Messenger

Video URL: https://youtu.be/geon2pM1xac

**Comment by raqeshmandhan** [comment]
@zhan1634 have you tested this? this scenario occurs, when you go to user portfolio and you haven't started chat with that user. and click on Message icon. instead of displaying that user in the messenger, it just opens the messenger.

**Comment by zhan1634** [comment]
this is updated in the next version
