### ISSUE TITLE
Follow/Unfollow user icon is inversed in Mobile App on Kebab menu (3 dots menu) on Ideas and Ideas Page

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#241]
Steps to reproduce/verify:
Go to Feed > Click on 3 dots on any idea > Follow User (Icon would be inverse)
Go to Feed > Click on Idea > check the Follow button (Icon would be inverse)

**Issue:** to follow a user, the icon appears that the user is already followed, and if a user is already followed, the icon appears that the user is unfollowed. 

Video URL: https://youtu.be/TmoJ__a1FKM

**Comment by zhan1634** [comment]
fixed in next release

**Comment by raqeshmandhan** [comment]
Okay, let me verify.
