### ISSUE TITLE
It shows the "Idea" link is copied in Mobile App, but its not usable and unable to send anyone

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#242]
Steps to reproduce:
Go to Feed > click 3 dots on any Idea > click "Copy Link"
                                **OR**
Go to Feed > Open any Idea > Click the copy link icon.

**Issue:** It seems the link is copied but we can't send the link to anyone else or use it in the browser.

Video URL: https://youtu.be/m7FPKSMRe_o

**Comment by zhan1634** [comment]
This has been updated.
