### ISSUE TITLE
Follow/Unfollow user must be updated in 3 dotted menu (kebab) on Idea and Idea page in Mobile and Web Application

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#243]
Steps to reproduce:

1. Go to user portfolio > unfollow user > go to Investment Feed >click on 3 dots menu (Follow/unfollow button would not have been updated yet).
2. Go to user portfolio > unfollow user > go to Investment Feed >Click on that user's idea > check the follow/unfollow button (it would not have been updated yet).

**Issue:** when we follow/unfollow a user from its portfolio, it must be updated on posted idea 3 dotted menu in "Investment Feed" and on the "Ideas" webpage.

Video URL: https://youtu.be/Vn33EFt31I4

**Comment by zhan1634** [comment]
Again this is a main feed refresh issue

**Comment by raqeshmandhan** [comment]
Yes, agreed.
