### ISSUE TITLE
Reported Idea shows the "Reported" initially but it must not update until Moderator/Administrator makes any changes 

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#244]
Steps to reproduce:
Go to "Investment Feed" > click on 3 dots on someone's idea and Report it> you will see "Reported" > go to Idea Page (Reported displays here too) > Now go to any random Page > again go to "Investment Feed" > click on 3 dots (you will find the report idea option again).

**Issue:** Once the idea has been reported, it must display the "Reported" option.

Video URL: https://youtu.be/8bCw0cVgaQk

**Comment by zhan1634** [comment]
Okay so you reported the idea, but the thing is that the back end did not update, if you refresh the page the error is gone. This is a minor issue to do with refreshes, but ill take a look. 

The thing with refreshes is that there's a fine balance between refreshing on every load - which slows down the app
