### ISSUE TITLE
If the reported Idea is deleted by the Moderator, it must not display in "Feed" / "Investment Feed" in mobile and Web Application.

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#245]
Steps to Reproduce:

1. Sign in on Utradea with Moderator Access > Report any idea from "Investment Feed" Page > Delete that Idea from "Moderator" module > Click on "Investment Feed".
2. Login in Mobile Application > Report any Idea from "Feed" page > Delete that Idea from "Moderator" on web > Click on "Portfolio" or any other page in Mobile application > Click on "Feed" again > the Idea will not be removed from "Feed".

"Issue:" The "Idea" must be removed from "Feed"/"Investment Feed" when deleted by the Moderator.

Web Video URL: https://youtu.be/Y6EI0hyJ3jo
Mobile Video URL: https://youtu.be/9QvzZsD7toA

**Comment by zhan1634** [comment]
this has now been updated

**Comment by raqeshmandhan** [comment]
@zhan1634  This issue still exists in Web and Mobile App. The idea isn't removed until a user restarts the app or reloads the web
