### ISSUE TITLE
[HIGH] [APP] follow user does not work in single position

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#249]
desktop does not have this issue

- following someone does not reflect when going to their page
- a user that i don't follow shows as following in single position

![adfwefad](https://user-images.githubusercontent.com/14366944/116736215-95ad2e80-a9bd-11eb-955f-837ac3054abd.jpg)

**Comment by zhan1634** [comment]
should be fixed in next update

**Comment by graceeguo** [comment]
recreate:
go to a position
follow user from position
go to profile 
unfollow user from profile
go back to position 
- either back button OR
- go to same position by going through feed first 

still says following
