### ISSUE TITLE
Portfolio page - Color of gain / loss % on active ideas is not based on whether it's positive or negative

### ISSUE THREAD

**Issue by leiron-james** [Utradea-Inc/utradea-public#25]
Please look into the coloring (green / red) logic on the mobile view.

![image](https://user-images.githubusercontent.com/78940042/108079782-2f12a880-703d-11eb-9952-1667554efc0e.png)

**Comment by zhan1634** [comment]
Resolved in update V3.7.1: Release - February 16th at 11:59 PM EST.
