### ISSUE TITLE
[LOW] [APP] default theme doesn't work

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#251]
- 'default' theme was never changed yet 'utradea' is applied here
- change from 'default' to mango works, but changing from mango to 'default' still shows 'utradea'

![adsfasdfads](https://user-images.githubusercontent.com/14366944/116736305-b5dced80-a9bd-11eb-8c37-970cc25ca9a3.jpg)

**Comment by zhan1634** [comment]
resolved in next update
