### ISSUE TITLE
[MED] many reddit posts need manual filtering?

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#253]
a lot of the tickers are not actually what the threads are talking about, many examples shown below

![asdf](https://user-images.githubusercontent.com/14366944/116736791-5a5f2f80-a9be-11eb-8eb4-ff545c038146.png)
![asdfegdfgh](https://user-images.githubusercontent.com/14366944/116736792-5a5f2f80-a9be-11eb-8580-aacfe7863101.jpg)
![dfghrtdgh](https://user-images.githubusercontent.com/14366944/116736793-5af7c600-a9be-11eb-8f86-c34472e0596f.jpg)
![dfghrtdhgf](https://user-images.githubusercontent.com/14366944/116736794-5af7c600-a9be-11eb-94ef-708725dabd5c.jpg)

**Comment by zhan1634** [comment]
We need to work on this algorithim a lot more

**Comment by zhan1634** [comment]
bug moved to utradea-client
