### ISSUE TITLE
[LOW] [APP] news (only) does not disappear when unsaved (in the saved page)

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#256]
ideas and sec/spac disappear right away
news goes away after a page refresh

![asdfewaf](https://user-images.githubusercontent.com/14366944/116737237-fb4dea80-a9be-11eb-94b6-8530bfaed886.jpg)

**Comment by zhan1634** [comment]
This is because the news that was saved was from our old news model, new news saved should be fine. Please check. This will naturally weed itself out.
