### ISSUE TITLE
Mobile App is taking too load on typing something (commenting, editing bio in setting)

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#260]
Video URL: https://youtu.be/sHUqQ3LjAjk

**Comment by zhan1634** [comment]
Is this on a simulator? It looks like a device issue and not an app issue.

**Comment by raqeshmandhan** [comment]
I think this is a device issue because it was working fine earlier. I'm using Vysor for screen mirroring on my desktop.
