### ISSUE TITLE
the image icon has old picture, if the user has updated his/her picutre in Mobile and Web App

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#261]
You can find the attached screenshot below:

![image](https://user-images.githubusercontent.com/28144322/116797935-33127a80-ab04-11eb-8924-fac10a0ec6b6.png)

**Comment by zhan1634** [comment]
Not a bug, this is just a timestamp request - in the future we will sync up the timestamps.

**Comment by raqeshmandhan** [comment]
Okay, closing this issue now.
