### ISSUE TITLE
[MOBILE APP] "News" title is different in "Feed" 

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#263]
Every "News" record have different title in Mobile App, you can find this in the attached screenshot below: 

![image](https://user-images.githubusercontent.com/28144322/116798422-b6ce6600-ab08-11eb-903f-1648efc9890a.png)

**Comment by zhan1634** [comment]
This is dynamic and randomly generated - there's a variety of titles it sorts through - this is not a bug.

**Comment by raqeshmandhan** [comment]
okay, noted.
