### ISSUE TITLE
[MOBILE APP] Notification badge is not shown (if the user receives any notification) until a user restarts the App

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#265]
Steps to Reproduce:

1. Login with the first user in App
2. Login with the second user on the Web.
3. Now, follow the first user.  (Notification badge will not be shown)
4. Restart the App, Now the notification badge will be shown

**Issue: ** The Notification Badge must be shown without restarting the Application

**Comment by zhan1634** [comment]
updated in next release
