### ISSUE TITLE
[MOBILE APP] On updating to the Dusk Theme, a user is unable to view the portfolio

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#266]
When the portfolio theme is set to Dusk, a user is can't view its portfolio. the screenshot is attached below:

![image](https://user-images.githubusercontent.com/28144322/116799463-0580fd80-ab13-11eb-8bd4-e1226e9a24ed.png)

**Comment by Ashish8822** [comment]
Is this happening only in mobile application ? As i can't find this on web

**Comment by zhan1634** [comment]
resolved in next update

**Comment by raqeshmandhan** [comment]
@Ashish8822 it worked fine earlier. Let me test it on the web today.
@zhan1634 Testing this now.
