### ISSUE TITLE
[MOBILE] [WEB] If the saved "Idea" is deleted by someone (moderator), it must be removed Saved Ideas.

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#271]
If the saved "Idea" is deleted by someone (moderator), it must be removed Saved Ideas. The issue exists on the Web and Mobile Application.

Steps to Reproduce: 

1. Report any Idea from "Feed"
2. Save the Idea
3. Now, delete the Idea by the "Moderator" user.
4. check the "Saved" Ideas. 

**Issue:** The idea will still be available in the "Saved" items, though it has been deleted.

**Comment by zhan1634** [comment]
No this is fine, they can still have that idea open. They just can't access it.

**Comment by raqeshmandhan** [comment]
Okay, Noted.
