### ISSUE TITLE
[WEB] The idea doesn't open on clicking the Idea from Search Ideas options, If you have already opened an Idea.

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#272]
Steps to Reproduce:

1. Go to "Investment Feed"
2. Open any "Idea"
3. Click on the Search button and then click on Ideas
4. Now, search for any idea and click any idea to open it.

**Issue:** You will see you will not be redirected to that Idea, The user must be redirected to that Idea.

Video URL: https://youtu.be/WQ1B3l9W3qo

**Comment by zhan1634** [comment]
updated in next release
