### ISSUE TITLE
In admin dashboard the idea gets deleted by clicking on delete button without having confirm delete prompt . 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#276]
If admin by mistake click on delete button it will delete the post. Instead we should have a confirmation prompt box do you want to delete . 
Screen recording : https://share.vidyard.com/watch/7MrgSeZpehFdYXjVr6A4xf?

**Comment by zhan1634** [comment]
this is okay, this is done by an admin.
