### ISSUE TITLE
Log in app- Impossible to log in app use account from website

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#28]
**step to reproduce:**
1. Open mobile app
2. Enter login and password from website account

Actual result:
Error message Email or UserName doesn't exist

Expected result:
Successful log in

**Comment by zhan1634** [comment]
This doesn't make any sense. First the app uses utradea.com, not beta.utradea.com, so you need an account on the actual website. The app and mobile are linked as one, so if you can log in with one you can log in with another. Closing this issue as this is just the tester unaware of what platform they are on.

**Comment by nonameuser2019** [comment]
I don't know it when I began
