### ISSUE TITLE
Update profile- Mobile app- Impossible click on icon of foto camera that update profile photo.

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#29]
Redmi 5 plus Android 8.1

Step to reproduce:
1. Log in app
2. Click on more
3. Click on setting
4. Click on icon photo camera to change photo

**Actula result:** Icon dosn't clicable

**Expected Result:** Opened window to upload photo
**Screen:** https://prnt.sc/zr0mji

**Comment by zhan1634** [comment]
This works fine on both android and IOS. Can you please elaborate? I cannot recreate the issue.
