### ISSUE TITLE
after logging in, if a user clicks on the messenger, the messenger does not open properly until Page is refreshed

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#293]
Steps to Reproduce:
Login with a user > Click on Messenger (Though the URL would be accurate but messenger won't be opened) > Now, Refresh the page (The messenger will open with chats available).

**Issue:** The messenger is not opening on the first click and it just results in the blank page.

Video URL: https://youtu.be/Gq2vSM-9114

**Comment by zhan1634** [comment]
I cannot replicate this, can you try replicating this again?

**Comment by raqeshmandhan** [comment]
Yes, Its still happening on my side. you can check this on this Video:  https://youtu.be/dVZ2R7C3Dgw

**Comment by Ashish8822** [comment]
try in incognito mode , as its working fine for me in every browser

**Comment by raqeshmandhan** [comment]
Yes, It's working fine on incognito @Ashish8822. I'm closing the issue.
