### ISSUE TITLE
[LOW] [UX] replace sending message icon

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#296]
![image](https://user-images.githubusercontent.com/14366944/117716446-9a38ca80-b1a7-11eb-880d-eb3ca2bed220.png)

currently: the send button loads -> usually indicates a connectivity issue
improve: send out the message but have the chat box have the loader beside it

**Comment by zhan1634** [comment]
this requires a major backend overhaul - will wait on this for a bit
