### ISSUE TITLE
[MED] [UI] checkmark replace with an X or filled checkbox in create group chat

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#298]
![image](https://user-images.githubusercontent.com/14366944/117716839-116e5e80-b1a8-11eb-8800-eaa181774218.png)

current: the action is to indicates that this user is selected for the group chat -> unintuitive
improve: the action is to indicate that you want to deselect the user from the group chat -> replace with X or filled checkbox

**Comment by zhan1634** [comment]
THIS IS NOT A MEDIUM UI BUG. fixed
