### ISSUE TITLE
[LOW] idea user follow/unfollow inconsistent with user page [WORKAROUND?]

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#299]
![image](https://user-images.githubusercontent.com/14366944/117717088-5a261780-b1a8-11eb-9974-fef6e60aafbd.png)

recreate:
1. go to idea 
2. follow user from idea page
3. go to user's portfolio
4. unfollow user from portfolio
4. go to user's idea tab
5. go back to same idea
6. still shows following

but going back to the feed, refreshing the feed, and going back to the same idea doesn't show this issue

**Comment by RajnishKatharotiya** [comment]
@zhan1634  Resolved in static, can you please close this one?
