### ISSUE TITLE
High priority : When we go to search page and then first search for any user and then click on crypto search , the page goes complete blank

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#302]
Steps
1. Login
2. Click on search button 
3. Click on user 
4. Search for any user
5. Now click on crypto search
6. Observe

Screenshot: https://share.vidyard.com/watch/Ww23VgXc9VDurTjDNjWDH9?

**Comment by zhan1634** [comment]
Updated in the next release
