### ISSUE TITLE
Even after the reported idea is unreported by admin , it still show reported , flag mark is still red

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#307]
Screen recording: https://share.vidyard.com/watch/bbjvM2z9v2XTcJeygUJDkp?

**Comment by zhan1634** [comment]
This is not a bug, if the report has been flagged, but deemed safe, it doesn't remove the original flag. If more people flag it we might monitor it again, this prevents the user from constantly flagging it.
