### ISSUE TITLE
The Line bar diagram displays the fluctuation in price but its value is 0.00 for FEG i

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#309]
The price value remains 0.00 in all time and in price line bar diagram You can find this in the attached image below:

![image](https://user-images.githubusercontent.com/28144322/117875908-276d4380-b2bc-11eb-9e39-7767543f1d9d.png)

**Comment by graceeguo** [comment]
i would highly suggest changing the '0.00' to '~0" or something
sigfig screams 'i am very accurate, therefore price is exactly 0'

**Comment by stuartjm5** [comment]
updated
