### ISSUE TITLE
While Posting the Idea from crypto page, The selected crypto must be available at "Ticker and Sentiment" Step

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#310]
Steps to Reproduce:
Search any Crypto > Click on Pencil icon for posting the idea > Press back step for going to "Ticker and Sentiment" Step

Video URL: https://youtu.be/hEPAPXTWPd8

**Comment by zhan1634** [comment]
resolved in the next release
