### ISSUE TITLE
Typing the currency name on "Post an Idea" must appear the result with correct crypto name

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#313]
You can find the attached screenshot(s) below: (This issue also exist in crypto search bar)

![image](https://user-images.githubusercontent.com/28144322/117883000-54255900-b2c4-11eb-934d-c596cb4d9c5c.png)

![image](https://user-images.githubusercontent.com/28144322/117883101-6f906400-b2c4-11eb-800d-a52440cd0f47.png)

**Comment by zhan1634** [comment]
resolved in next version

**Comment by raqeshmandhan** [comment]
@zhan1634 this is resolved but If I'm typing XRP, ADA etc. Now, I'm not getting the results.
