### ISSUE TITLE
the number text is out of rectangle.

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#315]
Screenshot attached below: 

![image](https://user-images.githubusercontent.com/28144322/117885727-9ef4a000-b2c7-11eb-9edc-75a0c14c88f8.png)

**Comment by zhan1634** [comment]
Im not sure why your percent gain so high.... this is not a bug in mine. Can you try to replicate it again

**Comment by raqeshmandhan** [comment]
@zhan1634 I'll surely try this again.
