### ISSUE TITLE
Convert vertical to horizontal rotation- App redirect to authorization page and to back to main page app.

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#32]
Redmi 5 plus android 8.1

**Step to reproduce:**
1. Log in app
2. change the device to horizontal

**Actual result:** Redirect to authorization page and come return to main page
**Expected result:** Change to horizontal

screen: https://prnt.sc/zr880f

**Comment by zhan1634** [comment]
Resolved in update V3.7.2: Release - February 17th at 11:59 PM EST.

**Comment by nonameuser2019** [comment]
fixed
