### ISSUE TITLE
[MOBILE WEB] Getting Error 404 page not found when clicked on "Write your Idea" from Price Section

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#324]
Steps to Reprodcue:

Click on Prices button from bottom menu > Click on "write your Idea"

Screenshot Attached below:
<img width="360" alt="Screen Shot 2021-05-13 at 8 05 50 PM" src="https://user-images.githubusercontent.com/28144322/118145039-8fd83400-b426-11eb-8cba-3dd76b723c0a.png">

**Comment by zhan1634** [comment]
updated in next relase
