### ISSUE TITLE
Windows 10 - Left Bar Overlap

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#329]
<img width="916" alt="Screenshot 2021-05-14 160152" src="https://user-images.githubusercontent.com/84204695/118322924-e0ef3300-b4cd-11eb-9c25-7bcd01ead9ad.png">

Hope this helps visualize my problem, also my zoom is on 100% so it wouldn't be a problem with that!

**Comment by zhan1634** [comment]
this is mainly due to screensize will be updated in the following versions when we move to ssr
