### ISSUE TITLE
[WEB] [MOBILE WEB] User is unable to search the Crypto with shorthand representation in Crypto Search Bar

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#330]
If you type Ripple the result will appear but If you type XRP the results will not appear
You can find the attached screenshot(s) below:

![image](https://user-images.githubusercontent.com/28144322/118332128-078b8900-b523-11eb-9f8c-09c3b3223d68.png)

![image](https://user-images.githubusercontent.com/28144322/118332178-183bff00-b523-11eb-94ea-6bf3ae87e692.png)

**Issue:** The Ripple crypto results must appear in both cases

**Comment by zhan1634** [comment]
updated in next release
