### ISSUE TITLE
[APP] User is unable to search the Crypto with shorthand representation in Crypto Search Bar

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#333]
Screenshot Attached Below:

<img width="355" alt="Screen Shot 2021-05-16 at 2 57 13 PM" src="https://user-images.githubusercontent.com/28144322/118393138-efb52180-b656-11eb-8b5e-1d9c87d5e16a.png">

![image](https://user-images.githubusercontent.com/28144322/118393209-533f4f00-b657-11eb-9e72-475b6b0e9b9f.png)

**Comment by zhan1634** [comment]
This is fixed in the next version
