### ISSUE TITLE
[APP] Unable to open trending crypto from "Trending Crypto Coins" 

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#334]
Steps to Reproduce:
Search any Crypto from Crypto Search Bar > Scroll Down to "Trending Crypto Coins" Section > Click on any crypto from the section

**Issue:** the section is not clickable and therefore unable to click on any trending crypto.

Screenshot attached below: 

![image](https://user-images.githubusercontent.com/28144322/118393404-6272cc80-b658-11eb-9c49-83f4312504e0.png)

**Comment by zhan1634** [comment]
Updated in next update
