### ISSUE TITLE
[APP] though the idea is saved but it seems the idea is not saved in mobile app 

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#335]
Screenshots attached below:

![image](https://user-images.githubusercontent.com/28144322/118394196-97811e00-b65c-11eb-90f2-74a6c61819bd.png)

![image](https://user-images.githubusercontent.com/28144322/118394186-8cc68900-b65c-11eb-8449-9807fa36ab8d.png)

**Comment by zhan1634** [comment]
You would need to reload the application - this is with every app, we can try to reduce the delay but this is not a bug - go to your saved items, if it is missing from there it is a bug

**Comment by raqeshmandhan** [comment]
@zhan1634 Okay noted. I'll try this scenario.
