### ISSUE TITLE
It is not possible to select a forecast for the future (bulls or bears) when clicking on the "give forecast" button from the cryptocurrency page (skips 1 step)

### ISSUE THREAD

**Issue by LilkitFutDev** [Utradea-Inc/utradea-public#339]
Attachment: https://www.dropbox.com/s/kbw9wpmuhj6ujqu/bandicam%202021-05-17%2010-31-11-035.mp4?dl=0

**Comment by zhan1634** [comment]
This is fine, if they want to re-write it then can go back one step to update.
