### ISSUE TITLE
Priority 3 - Profile image on single position page is enlarged and quality is poor (Desktop and App)

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#340]
The image becomes  "zoomed in" and doesn't look great, especially if someone uses a profile picture.

![image](https://user-images.githubusercontent.com/74615189/118548874-c8c72000-b728-11eb-86f0-4a310a73544b.png)

**Comment by zhan1634** [comment]
![image](https://user-images.githubusercontent.com/30502801/118567363-abec1600-b743-11eb-8e44-b17a697f2c25.png)

The images are pretty clear it depends on the quality of the photo you upload. For this one in particular it was a default image from Google which the default using thumbnails - if you upload a higher quality photo this issue doesn't occur
