### ISSUE TITLE
[DESKTOP] [LOW] [UX] not all stocks in database has a channel or they're not prioritized by exact word search

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#342]
![image](https://user-images.githubusercontent.com/14366944/118570368-04bead00-b74a-11eb-8a9a-32478546240e.png)

aapl exact search doesn't show aapl as first

**Comment by graceeguo** [comment]
![image](https://user-images.githubusercontent.com/14366944/118570390-11db9c00-b74a-11eb-9b04-c9e7bb513a16.png)

tsla not even listed

**Comment by zhan1634** [comment]
TSLA was not added, and search functionality is not from our end its from their end
