### ISSUE TITLE
[DESKTOP] [LOW] [UI] empty idea leaders?

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#343]
![image](https://user-images.githubusercontent.com/14366944/118570512-5109ed00-b74a-11eb-8b06-be47049f3328.png)

image removed, new one required or is old missing?

**Comment by RajnishKatharotiya** [comment]
We don't have image for empty idea and watchlist leaderboard.

**Comment by zhan1634** [comment]
@graceeguo can you design something for this? the old one wasn't that good

**Comment by RajnishKatharotiya** [comment]
@zhan1634 Resolved, can you please close this one?
