### ISSUE TITLE
[DESKTOP] [MED] [UX] block type box while loading

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#345]
![image](https://user-images.githubusercontent.com/14366944/118570668-9a5a3c80-b74a-11eb-912f-4961b2930a37.png)

case:
- user types 'lmao'
- press send
- continue typing next message 'asdf'
- appears alongside 'lmao' in the same box even though they are separate messages

mostly problematic for spam/fast typers (prob most people though tbh)

**Comment by zhan1634** [comment]
there was some throttling going on from their end last night - this should be updated and not occur anymore
