### ISSUE TITLE
[DESKTOP] [HIGH] [UX] [will be fixed?] need notifications for channel chat!!

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#347]
![image](https://user-images.githubusercontent.com/14366944/118570952-1c4a6580-b74b-11eb-87ae-dac08f2fba2c.png)

+ specific channel where the notif is coming from

**Comment by graceeguo** [comment]
![image](https://user-images.githubusercontent.com/14366944/118570989-2ff5cc00-b74b-11eb-8e30-747c21761c23.png)

specific channel example^

**Comment by zhan1634** [comment]
Updated in the next version
