### ISSUE TITLE
Text formatting issue with saved position cards

### ISSUE THREAD

**Issue by vlynchn** [Utradea-Inc/utradea-public#35]
<img width="962" alt="Screen Shot 2021-02-16 at 9 54 51 PM" src="https://user-images.githubusercontent.com/79173609/108162305-b5f96c80-70a1-11eb-8890-fc8040cc5794.png">

**Comment by zhan1634** [comment]
Resolved in update V3.7.2: Release - February 17th at 11:59 PM EST.
