### ISSUE TITLE
[DESKTOP] [MED] [UX] chat photo upload appearing as previous upload

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#351]
![image](https://user-images.githubusercontent.com/14366944/118571285-b4e0e580-b74b-11eb-9e08-b501b671b3c8.png)
![image](https://user-images.githubusercontent.com/14366944/118571290-b7dbd600-b74b-11eb-91ba-bad57f7909da.png)
![image](https://user-images.githubusercontent.com/14366944/118571294-bad6c680-b74b-11eb-95c1-f805b3f9d55e.png)

case:
- upload photo1
- send
- appears in chat as photo1
- upload photo2
- send
- appears in chat as photo1 (pop-up is still photo2)

**Comment by zhan1634** [comment]
Latency - should be fixed in next release
