### ISSUE TITLE
[DESKTOP] [MED] [UX] closed ideas should list in most recently closed

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#355]
![image](https://user-images.githubusercontent.com/14366944/118571686-9b8c6900-b74c-11eb-8d6c-6cddb7fa68a1.png)

seems like it's listed as most recently ADDED
- i closed mnst, bpop, then tsla in that order, but it appears as above because i added tsla, mnst, bpop to my watchlist in that order

**Comment by zhan1634** [comment]
kk updated in the next release
