### ISSUE TITLE
Page is getting logout and logged in back automatically after clicking in back button.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#36]
When user click on back button the page is getting logout and logged in back automatically.

Please see refer screencast: https://screencast-o-matic.com/watch/crnDYNSpML

Mobile version issue.

**Comment by zhan1634** [comment]
What is the expected result? Log out? You can log out at the bottom. Given that you are signed it, this should be the correct action, because you are going back to the log in page, but you are already logged in so it redirects you.
