### ISSUE TITLE
[MOBILE] [MED] [UX] users should have option to un-report idea or...

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#372]
or... [UI] increase space between report and other buttons OR make the dropdown bigger (clumsy finger-ed people)
![image](https://user-images.githubusercontent.com/14366944/118929897-169f7c00-b913-11eb-81f4-f33af5a9a066.png)

**Comment by zhan1634** [comment]
in the future we can add a further pop up for like reason on why we need to report it - for now we can leave it
