### ISSUE TITLE
[MOBILE] [HIGH] [UX] need to tap menu items multiple times to register because the tap goes into the idea ?

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#373]
![image](https://user-images.githubusercontent.com/14366944/118930108-536b7300-b913-11eb-9a13-a0de6960fabc.png)

is this a my phone issue? galaxy s10 samsung internet browser
the blue box (selection) appears anytime i try to tap the menu icon (3 dots) or any of the dropdown items

**Comment by zhan1634** [comment]
udpated in the next release
