### ISSUE TITLE
[ALL] [MED] [UI] have 0% returns be grey/white/notred/notgreen

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#375]
![image](https://user-images.githubusercontent.com/14366944/118930515-d7255f80-b913-11eb-899f-cc58a5a22ade.png)

 confusing

**Comment by graceeguo** [comment]
confusing because some 0% returns are green some are red**

**Comment by RajnishKatharotiya** [comment]
@zhan1634 made it default style if gain is 0, can you please close this one?
