### ISSUE TITLE
[ALL] [DEMO] [MED] [UX] change search bar for stocks also change wording

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#377]
![image](https://user-images.githubusercontent.com/14366944/118931187-ae519a00-b914-11eb-90d5-54ad895ba419.png)

Block ability to press into search bar (and type), replace 'Search' with white text 'TSLA'
change wording prompt to:
Sign in to Utradea and search for over 30k stocks!

**Comment by RajnishKatharotiya** [comment]
@zhan1634 Resolved into state, can you please close this one?
