### ISSUE TITLE
[ALL] [DEMO] [HIGH] typo + grammar mistake in user search bar

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#378]
![image](https://user-images.githubusercontent.com/14366944/118931424-fe306100-b914-11eb-85fe-bf075803ebba.png)

'Sing in to search any users from Utradea.' to
'Sign in to search all users on Utradea.'

**Comment by zhan1634** [comment]
this is updated in the next release - but I plan to update search all together
