### ISSUE TITLE
[MOBILE] [DEMO] [HIGH] [UX] clicking anything that prompts a login won't allow me to go back to demo

### ISSUE THREAD

**Issue by graceeguo** [Utradea-Inc/utradea-public#379]
![image](https://user-images.githubusercontent.com/14366944/118932156-b78f3680-b915-11eb-8354-1f024ac83991.png)

example recreate:
1. on demo
2. go into idea
3. click on view full feature chart
4. takes me to login page
5. go back via browser back button
6. can't, just refreshes the login/signin page

**Comment by RajnishKatharotiya** [comment]
@zhan1634 we can close this one, we are not using this cards anymore.
