### ISSUE TITLE
Problem in watchlist rank calculation in portfolio tab

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#38]
**Steps to reproduce**
1. Go to https://beta.utradea.com
2. Log in to account
3. Click on "Portfolio tab"
4. Remove all the watchlist and observe the watchlist rank
5. Go to investment tab open any idea and click on add to watchlist button(+)
6. Perform step 5 two or three times
7. Now go back to portfolio tab and observe the watchlist rank result

Actual Result : Watchlist rank remain same even if we delete all the ideas and and different ideas to watchlist.
Excepted Result: Watchlist rank should change accordingly.
Video : http://somup.com/crnb6ED3Zu

**Comment by zhan1634** [comment]
Your watchlist rank is based on the returns of your watchlist. Given your video, nothing moved so your watchlist rank won't move.
