### ISSUE TITLE
[Feature/UX Request]

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#383]
1) Having a button to get to the next idea would help people save a bit of time and be easier. Both on people's profile when they are viewing ideas and if they are looking at the ideas about a certain stock.

2) Could the "Ideas" tab be the default when viewing a profile rather than the "portfolio" tab. I find I am always clicking to get to peoples ideas and it would be a little bit more user friendly. 

 #Thanks``

**Comment by zhan1634** [comment]
Updated in the next release
