### ISSUE TITLE
[FEATURE] Keeping track of where you left off while scrolling on mobile

### ISSUE THREAD

**Issue by lisav-03** [Utradea-Inc/utradea-public#384]
When scrolling through the investment feed on a mobile device, when you click onto an idea to read and then go back to the investment feed by clicking the top left arrow it takes you back to the very top of the feed and not where you left off. It's hard for users when they scroll very far down and then having to find where they left off after they finish reading.

**Comment by zhan1634** [comment]
For sure! We are aiming to update this - sorry could you please clarify is this in the iOS / android apps or just the mobile web?
