### ISSUE TITLE
[Mob app] when user login with already registered account it show verify email 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#385]
screenshot. https://screencast-o-matic.com/watch/crhrDMVfLJv

**Comment by callanmurphy** [comment]
Seems to only be an issue on the beta/local server. Checked using the production server and the verification bar disappears. Email verification is done through api.utradea.com I imagine @zhan1634 ?

**Comment by zhan1634** [comment]
No email verification is on beta and production
