### ISSUE TITLE
Problem in leader section % calculation in portfolio tab 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#39]
**Steps to reproduce**
1. Go to https://beta.utradea.com
2. Log in to account
3. Click on "Portfolio tab".
4. Go to "Leader section".
5. Open any one of them and see its value.
6. Go back and in leader section compare that value from step 5.

Actual result: Leader section is showing 0.00% in every ticker but when you open the ticker its value is different.
Excepted result: %value of leader section should not show 0.00% for every ticker it should show accordingly.
Video : http://somup.com/crnbX6D3OP

**Comment by zhan1634** [comment]
This is not an issue because you earned 0% since you entered it. This is not tracking the stock's performance, but rather your portfolio performance. Please let me know if you need further clarification.
