### ISSUE TITLE
[Feature] - Portfolio of Ideas - Tagging

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#393]
For the fellow analysts (like me), I think it would be awesome to have more idea sections available. 
I think that the best way to go about this is to offer "portfolio's of ideas" in which users have 5 "portfolios" of 10 ideas that they can name and alternate through.
Also, if the UTradea Analysts could have special profiles with a verified icon that allows only them this access that would also be neat.
I think this is good for users because if they find a favourite analyst, they can follow them and see all of their ideas. Rather than jumping to and from their new and old profiles

**Comment by lisav-03** [comment]
I agree with this. Ex. I could do 1 portfolio could be blue-chip stocks, another portfolio can be for hype stocks etc and have all the portfolios under 1 user on utradea

**Comment by zhan1634** [comment]
In the new version, we will give you guys more positions, and the ability to tag certain stocks to certain portfolios. This is quite a significant feat on the backend, so just give us some time to put it on the road map

**Comment by stuartjm5** [comment]
moved to client
