### ISSUE TITLE
[ANDROID APP] - User cannot signup on app using FB or Google login - error for both (Samsung Galaxy s21)

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#396]

**Comment by callanmurphy** [comment]
![Screenshot_20210525-122126_Facebook](https://user-images.githubusercontent.com/55993520/119941833-1b8dac80-bf5f-11eb-8715-68cc888d853e.jpg)
![Screenshot_20210525-122144_Utradea](https://user-images.githubusercontent.com/55993520/119941836-1b8dac80-bf5f-11eb-9faf-c251a1e8d362.jpg)
Screenshots from Grace with error messages

**Comment by callanmurphy** [comment]
Still troubleshooting - no errors on iOS but expo doesn't allow for google sign-in testing + don't have an Android device so I'm attempting to test through an emulator. Might need a hand with this @zhan1634

**Comment by callanmurphy** [comment]
@zhan1634

**Comment by zhan1634** [comment]
closed in next release
