### ISSUE TITLE
STATIC PAGE: Typos and Old Data

### ISSUE THREAD

**Issue by vicxnguyen** [Utradea-Inc/utradea-public#399]
<img width="367" alt="Screen Shot 2021-05-24 at 7 04 33 PM" src="https://user-images.githubusercontent.com/50087329/119417194-478d0180-bcc3-11eb-86f6-1a3d6affab1f.png">

capabilitiess -> capabilities 
watchist -> watchlist 

<img width="447" alt="Screen Shot 2021-05-24 at 7 04 10 PM" src="https://user-images.githubusercontent.com/50087329/119417269-6ee3ce80-bcc3-11eb-82e7-3130847ef1f0.png">

analyss -> analysis 
Acces -> Access 
change April 2021 to "Coming Soon" - as we do not have in platform trading yet 

<img width="399" alt="Screen Shot 2021-05-24 at 7 06 55 PM" src="https://user-images.githubusercontent.com/50087329/119417368-a94d6b80-bcc3-11eb-8128-901ef888aa4c.png">

We no longer have payout option, so we should remove "User Payouts" from the table to avoid confusion of new users

**Comment by graceeguo** [comment]
https://www.figma.com/file/qYKv3PLmMP0PP8gmmk9oU7/?node-id=20%3A305

pricing table updated^ graphics for desktop, tablet, and mobile in the link above
timeline will be scrapped and changed to something else

**Comment by RajnishKatharotiya** [comment]
@zhan1634 @graceeguo Updated images of price table.
