### ISSUE TITLE
Inaccurate data  in Top Sector and Top Industry in portfolio tab

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#40]
**Steps to reproduce:**
1.Go to https://beta.utradea.com
2. Log in to account
3. Click on " Portfolio tab "
4. Remove items from watchlist or add new items to watchlist
5. Observe value in "Top industry and Top Sectors"

Actual result: Value in Top industry and Top sectors are constant even if we add or delete items from watchlist
Expected result: Value should change accordingly.
Video: http://somup.com/crnblfD3xx

**Comment by zhan1634** [comment]
When you close your watchlist, your position is closed. It's not supposed to change unless you add more sectors from a different area.
