### ISSUE TITLE
[STATIC] [MED] some demo features remain after logging in

### ISSUE THREAD

**Issue by callanmurphy** [Utradea-Inc/utradea-public#400]
logging in using the 'sign in/register' popup displays the correct profile picture but some links/attributes stay the same as demo

ex: the popup still appears despite being signed in
![Screen Shot 2021-05-25 at 3 22 32 AM](https://user-images.githubusercontent.com/55993520/119457112-526a8500-bd09-11eb-9cad-c30900764413.png)

**Comment by zhan1634** [comment]
what.. how is this.. even.. possible - can you show me?

**Comment by callanmurphy** [comment]
@zhan1634 yes if I can remember what wizardry I did to make it happen lol

**Comment by callanmurphy** [comment]
pretty sure this was due to a login timeout but it's not happening on the new beta site, probably fine to close this
