### ISSUE TITLE
Cannot send first message with user directly from their profile 

### ISSUE THREAD

**Issue by vicxnguyen** [Utradea-Inc/utradea-public#406]
<img width="1440" alt="Screen Shot 2021-05-27 at 2 43 10 PM" src="https://user-images.githubusercontent.com/50087329/119880098-e602a800-bef9-11eb-938d-ee0d0bddaeda.png">

If you do not have any existing chats open, you cannot send a message to a user directly from clicking on the message icon on their profile (it takes you to the generic "select or search user to start conversation" - which defeats the purpose of clicking on the message button from their profile in the first place).

**Comment by RajnishKatharotiya** [comment]
@zhan1634 fixed (same problem as #414 issue), can you please close this one?
