### ISSUE TITLE
Value inside top sector in ideas section of portfolio tab is constant

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#41]
Steps to reproduce :
1.Go to https://beta.utradea.com
2.Log in to account
3.Click on "Portfolio"
4.Navigate over ideas section
5. Try to close all the active ideas and observe the top sector values.
6. Now just add only 2 new ideas and again observe the top sector values.

Actual result: Values under the top sector is constant even if user remove all the ideas it still shows the same old value 
Excepted result: Value should change when user add or remove data 
Video: http://somup.com/crnblkD3zV

**Comment by zhan1634** [comment]
Did you add a new sector? If you add stocks from the same sector, it's only going to show you the sectors you are invested in. If you have 100 stocks in technology - it's only going to show one sector. Please clarify if this resolved your issue.
