### ISSUE TITLE
Click on Post an idea/write an idea redirects to the feed page instead of displaying pop up for sign in/register

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#410]
Video URL: https://youtu.be/lg1OTndu5wY

**Comment by RajnishKatharotiya** [comment]
Can't reproduce this one.

**Comment by raqeshmandhan** [comment]
did you tried after log in? I'm still able to do this by redirecting to the User's portfolio.

**Comment by zhan1634** [comment]
he is not logged in so it goes into position-upload then back to feed, I've disabled the link when the user is not logged in
