### ISSUE TITLE
Ascending/Descending filter is not working with respect to Date for Today's posted ideas in Saved Ideas

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#417]
Video URL: https://youtu.be/JrJ6famJM-g

**Comment by Ashish8822** [comment]
working fine for me

**Comment by raqeshmandhan** [comment]
@Ashish8822 I just added the wrong description. hope you will understand this now.

**Comment by RajnishKatharotiya** [comment]
@zhan1634 done, can you please close this one?
