### ISSUE TITLE
Mobile app- The problem after click on any ticket in watch list.

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#42]
Android 8.1 5.5 inch
Step of reproduce:
1. Log in the app
2. Open portfolio
3. Click any ticket on watchlist

Actual result:
The field of search receives a focus and open keyboard

Expected result:
The field of search dosn't recive a focus

This situation isn't comfortable for users
screencast:  https://dropmefiles.com/f2qRy

**Comment by zhan1634** [comment]
Resolved in update V3.7.2: Release - February 17th at 11:59 PM EST.

**Comment by nonameuser2019** [comment]
fixed
