### ISSUE TITLE
UI Issue on viewing Posted Idea

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#420]
Steps to Reproduce:
Select Post an Idea > Select Stock > Analysis Type > Idea & Catalysts > Position and Metrics > Title (here enter the maximum characters in Title)

Screenshot attachment below:

![image](https://user-images.githubusercontent.com/28144322/120012819-6eb43d80-bff9-11eb-91c5-abde05f7b2b9.png)

**Comment by Ashish8822** [comment]
i guess it will not occur when you will type whole paragraph not just a single word .

**Comment by raqeshmandhan** [comment]
You're right @Ashish8822

**Comment by zhan1634** [comment]
fixed
