### ISSUE TITLE
After log out, the user is still logged in

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#426]
Video URL: https://youtu.be/V7Qdfgsh89Y

**Comment by zhan1634** [comment]
ive updated the auth in the next release, can you see if you can replicate this? i really don't know how you did this lol

**Comment by raqeshmandhan** [comment]
Yes, I'll try again that.

**Comment by raqeshmandhan** [comment]
@zhan1634 this is still reproducible. You can follow the steps below to verify:

1. Login with a user
2. Go to settings and click logout
3. Now, click on link/button on right bottom for login where it's written "Enjoying Utradea? ..."
4. On Pop up, switch to the Register tab.
5. Click on "Already Have An Account? Sign In Here".
6. (Here you will be redirected to sign in Page) Click on the Portfolio icon from left menu.

**Comment by zhan1634** [comment]
Yeah I still cannot replicate this even following your steps

**Comment by raqeshmandhan** [comment]
May be we should connect over the call for this.
