### ISSUE TITLE
An unexpected error occurred on Feed (NOT REPRODUCIBLE)

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#429]
Screenshot attached below:

![image](https://user-images.githubusercontent.com/28144322/120086644-000ad900-c0fa-11eb-90b6-671ba8909fea.png)

**Comment by zhan1634** [comment]
plrease try to reprouce this bugs and create a new bug with the steps

**Comment by raqeshmandhan** [comment]
@zhan1634 noted.
