### ISSUE TITLE
Mobile app- Portfolio- The Items in Top sector and Top industries all time change position

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#43]
1. Go to mobile app
2. Click on portfolio

Watch screencast

video: https://dropmefiles.com/gD3kP

**Comment by zhan1634** [comment]
Resolved in update V3.7.2: Release - February 17th at 11:59 PM EST.

**Comment by nonameuser2019** [comment]
fixed
