### ISSUE TITLE
[MOBILE WEB] Idea posting option must not be available as it leads to 404 page not found

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#430]
Screenshots attached below:

![image](https://user-images.githubusercontent.com/28144322/120086710-cf776f00-c0fa-11eb-8459-f0172fbefe12.png)

![image](https://user-images.githubusercontent.com/28144322/120086720-d900d700-c0fa-11eb-8f84-9d6f4b4eea8a.png)

**Comment by zhan1634** [comment]
perfect bug - fixed in next release
