### ISSUE TITLE
Mobile App- Doesn't work exit from app use double click on button return

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#44]
Step of reproduce:
1. Log in the mobile app
2. Logout and try to exit from app

Actual result: Double click on button of return dosn't exit from app

expected result: successful exit from application

**Comment by zhan1634** [comment]
What do you mean by return ? Can you show a video

**Comment by nonameuser2019** [comment]
This bug doesn't reproduce again.
