### ISSUE TITLE
If a google/facebook account has been linked earlier. it must not be linked with the other user

### ISSUE THREAD

**Issue by raqeshmandhan** [Utradea-Inc/utradea-public#440]
Video URL: https://youtu.be/g8VI9w9EGhw

**Comment by zhan1634** [comment]
Okay my question for this... if you log in with google which account do you go in?

**Comment by raqeshmandhan** [comment]
@zhan1634 the latest one, that you have connected.

**Comment by zhan1634** [comment]
updated in the next release
