### ISSUE TITLE
Closed Ideas is displayed in "Fresh Ideas" section

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#45]
Steps to reproduce :
1.Go to https://beta.utradea.com
2.Log in to account
3. Click on Investment Feed
4. Click on "Fresh Ideas"

Actual Result: Closed Ideas are also displayed 

Expected Result: Closed Ideas should not be displayed in the "Fresh Ideas" section

Video: http://somup.com/crnbDcD3WB

**Comment by zhan1634** [comment]
This is okay because closing an idea is considered a "fresh" idea because there's an action taken upon it.
