### ISSUE TITLE
[Priority 3] - Link formatting for blog posts need to be updated - the links have /blog/ inserted so you can't link to the original post

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#450]
This is the original link I add to the blog post - https://utradea.com/positions/60a66cc09b12641993e41e2f
This is the link once it is posted on the blog - https://utradea.com/blog/positions/60a66cc09b12641993e41e2f
It adds /blog/ between utradea and position

**Comment by RajnishKatharotiya** [comment]
@zhan1634 Resolved, can you please close this one?
