### ISSUE TITLE
[Feature] - Next and Back based on where the query came from

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#452]
The "next article" button is fantastic, however, when you are on someone's profile and you click next it brings you to an unrelated analysis rather than their next post

**Comment by zhan1634** [comment]
This one is a bit tricky, but we can implement it, the redirect only redirects to a position, so it doesn't carry the history of where it comes from, for that to work, we need to implement a few other parameters which will take some time. This will be added to the roadmap but not as high of a priority.

**Comment by stuartjm5** [comment]
updated
