### ISSUE TITLE
[Priority 3] - Customer Journey - Have Reddit Tab Visible for Non Registered Users - make them sign up to access

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#457]
There is a lot of traffic that is driven from the Reddit dashboard - the problem is that when they land it isn't obvious that you can access the dashboard, so they drop off

![image](https://user-images.githubusercontent.com/74615189/120668729-bc4b0300-c45c-11eb-97fd-1c127e947f2f.png)

**Comment by RajnishKatharotiya** [comment]
@zhan1634 Added, we can close this one now.
