### ISSUE TITLE
Not able to preview idea when posting

### ISSUE THREAD

**Issue by lisav-03** [Utradea-Inc/utradea-public#459]
Not able to preview an idea before posting. It comes up as "An unexpected error has occurred"

![Screen Shot 2021-06-04 at 2 28 07 PM (2)](https://user-images.githubusercontent.com/84538678/120847198-250bab80-c541-11eb-8d8b-fbb44fb6118e.png)

**Comment by RajnishKatharotiya** [comment]
@zhan1634 Fixed, can you please close this one?
