### ISSUE TITLE
Letters coming outside the box in Active Idea section

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#46]
Steps to reproduce :
1.Go to https://beta.utradea.com
2.Log in to account
3. Click on Post an Idea, and select any ticker
4.  Add any idea under "General" section and click next & submit the idea.
5.  Type 100 words/letters under "Quick Intro" section, and click next 
6.  Click on "Click to Preview Your Position"
7. New tab will open & observe the result

Actual Result: Letter are coming outside the box and coming under the like button

Expected Result: Letter should be inside the box only.

Video: http://somup.com/crnbFDD0bP

**Comment by zhan1634** [comment]
Resolved in update V3.7.2: Release - February 17th at 11:59 PM EST.
