### ISSUE TITLE
Spacing issue on stocks page

### ISSUE THREAD

**Issue by lisav-03** [Utradea-Inc/utradea-public#466]
Spacing issue in the Brief Overview portion where the 'Read More' overlays with the other text

![Screen Shot 2021-06-09 at 5 07 25 PM](https://user-images.githubusercontent.com/84538678/121430234-d8134500-c945-11eb-9b54-051b847841ef.png)
![Screen Shot 2021-06-09 at 5 07 41 PM](https://user-images.githubusercontent.com/84538678/121430243-dba6cc00-c945-11eb-8148-166fa2497867.png)

**Comment by zhan1634** [comment]
Fixed in next update
