### ISSUE TITLE
[Priority 3] - make follow user button more explicit - see image below

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#474]
![image](https://user-images.githubusercontent.com/74615189/121972804-f4e6b880-cd49-11eb-9f10-cab2492e87a2.png)

**Comment by graceeguo** [comment]
author is not really the focus of that card to begin with, 
would not suggest a follow button there esp. beside the stock info
still kinda iffy about the follow button being so hidden, might as well just take it out at this point
seeing as users who are interested in the author would click on the author's name to go to their portfolio anyways

**Comment by stuartjm5** [comment]
moved
