### ISSUE TITLE
New additions to the drop and move dashboard

### ISSUE THREAD

**Issue by Adityaraghunath1** [Utradea-Inc/utradea-public#488]
We can look at add forward-looking metrics or estimates such as forward P/E, price to sales, EV/EBITDA as well as revenue and earnings estimates. Another solid feature that will attract users is to provide them with the average price target estimates for the particular stock, according to Wall Street. They can then filter stocks by their upside or downside potential.

**Comment by stuartjm5** [comment]
Was updated
