### ISSUE TITLE
Add the meta description option for each post/stock idea on Utradea.com

### ISSUE THREAD

**Issue by Adityaraghunath1** [Utradea-Inc/utradea-public#489]
Meta Descriptions are really important from an SEO point of view. It is basically a summary of the post that should be around 50 words (or less). The meta description should ideally have the targeted keyword as well. 

This is an example of the meta description. 
![image](https://user-images.githubusercontent.com/40269362/135001098-886025bd-6792-4416-b653-60a623e517d7.png)

**Comment by zhan1634** [comment]
Do we not have this?

**Comment by zhan1634** [comment]
![image](https://user-images.githubusercontent.com/30502801/135145172-cecda958-da63-4c6f-9c1d-30030812e3fa.png)

**Comment by zhan1634** [comment]
we have the title and then the sentiment. will update to just content.
