### ISSUE TITLE
User is not able to delete comment 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#49]
**Steps to reproduce:**
1. Go to https://beta.utradea.com/
2. Login to your account
3. Click on portfolio tab
4. Navigate to Ideas section
5. Select any active ideas and add comment to it and try to delete that comment 

Actual result: User is not able to edit or delete the comment .
Expected result : User should get an option to edit or delete the comment.
Video:  http://somup.com/crnFQ7DZ42

**Comment by zhan1634** [comment]
This is released in the next update -edit only
