### ISSUE TITLE
[Feature] - Quick Notes Function 

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#491]
Objective: Ability to quickly make notes while browsing the site where you can save content as you piece it together - helpful for traders or as you are conducting research

Feature 1: Ability to makes and save notes - essentially a notepad within Utradea

Feature 2: Ability to quickly post this "note" as a quick piece of info - longer than a comment or chat but shorter than a full upload (include ability to tag tickers?)

![image](https://user-images.githubusercontent.com/74615189/135173715-547e5b53-409b-4bf4-811a-a64923dc2043.png)

Something similar to this

![image](https://user-images.githubusercontent.com/74615189/135173938-cfb222d3-c199-4a3a-89a9-9cb4859017b1.png)

**Comment by graceeguo** [comment]
could prob save the notes alongside other saved in the save page

**Comment by Ameria3** [comment]
Following *love this
