### ISSUE TITLE
[Feature] - Make Info / Help / Disclaimers More Prominent

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#492]
Problem: Tough to find - important for new users

Feature: Add a quick link to the menu bar on the left?

![image](https://user-images.githubusercontent.com/74615189/135174415-4198ddbe-03f5-4bc4-acc0-a063f0011889.png)

**Comment by graceeguo** [comment]
ya down

**Comment by zhan1634** [comment]
In development
