### ISSUE TITLE
[Feature] [Position Upload] - Make the Steps in The Upload Position Buttons For Easy Navigation

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#493]
Objective: make navigation when uploading a position easier with clickable steps

Feature: Make the upload step buttons clickable

![image](https://user-images.githubusercontent.com/74615189/135174921-a6a3585a-123e-493c-9e34-16d815310ad0.png)

**Comment by zhan1634** [comment]
Moved to client for build
