### ISSUE TITLE
[Feature] [Position Upload] - Be Able Edit Bull Bear For Each Step

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#494]
Objective: Edit the Bull/Bear for the position at different steps

Feature: Make the bull and bear clickable at each step. In order to do this we need to have the PT with it because they go together

Option 1: Change the Card to include bull/bear and price target from step 2 onwards - so steps 2,3 and 4
Option 2: Keep the card, make it clickable and just show the resulting PT (+ or - 5%)

Note: Needs to be reviewed - if this is the best approach please assign to design

![image](https://user-images.githubusercontent.com/74615189/135175676-e1a71931-e556-482c-aa5c-a58a2205830b.png)

**Comment by zhan1634** [comment]
When this was first introduced, you could change bear / bull at any step. This led to a lot of complications and bugs - for the most part when people do their initial research they are either bullish or bearish at that step. That step may be determined at a later step, but should not be able to be flipped at different parts.
