### ISSUE TITLE
[Feature] [Feed] - Make Search Bar Fixed on Feed Page

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#496]
Objective: Make it more convenient to quickly search while browsing the site

Feature: Add search bar to the top of the feed page and make it fixed

Note: need to explore if it makes sense to do this on other pages on the site

![image](https://user-images.githubusercontent.com/74615189/135177117-ac5ea50f-810a-4662-8e40-2628630367f3.png)

**Comment by graceeguo** [comment]
a few ideas:
sticky at top yes, only on feed pages, shows instant results, can click on instant results or entering/search takes you to search page
search bar in left nav bar when it opens up on hover, maybe show instant results, searching takes you to search page
