### ISSUE TITLE
[Feature] [Portfolio] - Remove "Edit Active Idea" From A Persons Portfolio If They Don't Have an Idea

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#497]
Format Change / Suggestion - clean up / simplify the aesthetics a bit. Possibly change format. Here is another person’s profile. But they don’t have any closed ideas, possibly just show the N/A ideas available, not the default setting here

![image](https://user-images.githubusercontent.com/74615189/135190373-6e3182fa-94ab-4e49-a0e3-cde0a711c00d.png)

**Comment by graceeguo** [comment]
all the use cases have been in figma
pls update

https://www.figma.com/file/pizXCBgqeYUJwn6KP5bagT/Watchlist-and-Ideas?node-id=813%3A1885

**Comment by zhan1634** [comment]
Fixed in latest release
