### ISSUE TITLE
[Feature] - Create Functionality To Auto-claim your Reddit Account

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#498]
Objective: Allow users on Reddit to automatically claim their Utradea account when their ideas are auto posted so they don't have to contact support.

Priority: Low

Need to think about how this would work - an authentication similar to login with Google Account? I think the current process works for right now.

**Comment by Ameria3** [comment]
Following

**Comment by zhan1634** [comment]
Explain how this would work. Reddit Username does not equal email. How do you prove this?

**Comment by zhan1634** [comment]
Cannot be done unlessa process is thought through.
