### ISSUE TITLE
[Feature] [SEC Dashboard] - Show All SEC Filings For Each Company (Interim Steps in description)

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#499]
Objective: Allow users to see all the SEC filings for a company

Feature: The SEC dashboard will show all SEC filings in the Utradea view

Interim Fix: 
a) create link to SEC filing home page
b) create link to SEC filing stock specific page based on what stock you have filtered

![image](https://user-images.githubusercontent.com/74615189/135264324-ad3375dd-ec8f-482b-a7b2-8e104206e98f.png)

**Comment by Ameria3** [comment]
Following

**Comment by zhan1634** [comment]
Resolved in latest update.
