### ISSUE TITLE
[Feature] [Social Sentiment Dashboard] - Price Is Cut Off on Y Axis

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#501]
Update padding so price is visible

![image](https://user-images.githubusercontent.com/74615189/135266836-6c906ece-52af-415d-bddb-df4ca881e5fb.png)

**Comment by graceeguo** [comment]
ya i already raised this issue, but it's been closed https://github.com/Utradea-Inc/utradea-client/issues/758
not sure if issue would still exist for different monitor sizes but it is no longer an issue on either of mine

**Comment by zhan1634** [comment]
Fixed and released on Sept 30, 2021
