### ISSUE TITLE
[Feature] [Social Sentiment Dashboard] - Show Deltas for Mentions  and Comments

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#502]
Objective: Show the change in social chatter / sentiment 

Note: need to think about this design a bit more - assign to me - this might need to be a new chart or an updated table

What is our objective with this? Want to see how social sentiment correlates with price and if it can be used as a leading indicator?

**Original Comment:** Could you just do four different lines? Be able to show a change in price, change in mentions, change in
comments as separate lines? Might be easier to visualize. I do like the interactiveness of it with the turning on/off of measurements, but personally seems like a lot going on that can be simplified as a possibility. Oh, and price on the right side is cut off on the y-axis.

**Comment by Ameria3** [comment]
Following

**Comment by stuartjm5** [comment]
Another user requested to see the momentum of a ticker - how quickly it has changed. This would be able to show which ones are starting to spike or trend and would help eliminate the main tickers that are always on the top of the leaderboard. 

Comment from Reddit "Is there a way you could measure the rate of change, or momentum? This way, up and coming stocks would be closer to the top, as opposed to those stocks that have large but stable scores, such as TSLA or QQQ?"
