### ISSUE TITLE
[Feature] - Ability to Delete Account Without Contacting Support

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#503]
1. Create a button to automatically delete your account

Process:
1. click button
2. popup "are you sure you want to delete your account?" Y/N
3. If yes, "we are sorry to see you go" - include form that provides reasons why they are leaving and a comment box for them to leave written comments - essentially it would be good to know why the are deleting their account

![image](https://user-images.githubusercontent.com/74615189/135272908-c806cbbd-924a-492e-a60a-f0bdf3714e89.png)

**Comment by Ameria3** [comment]
Following

**Comment by zhan1634** [comment]
Do we expect people to delete their account? If so, just contact support.
