### ISSUE TITLE
[Feature] [Portfolio] - Authority Score Payout - Show only $ earned and Provide more detail about payment formula

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#504]
Objective: Incentivize users to past content and increase their potential payout

Update:
1) only show "earned to date" and not number of views
2) create a link to "how the authority score works" page
 - This will have an explanation of Authority Score and how it's calculated
 - we want to be transparent but don't want to provide everything - show just the formula? 
 - need to determine what info to show 
 - something similar to Seeking Alpha article 
 
 https://seekingalpha.com/page/article_payments

**Comment by graceeguo** [comment]
duplicate tag see: https://github.com/Utradea-Inc/utradea-public/issues/509
styling tag: take out view count vs. not, ya tbh i'd take out view count because social anxiety things but it does work...

**Comment by stuartjm5** [comment]
Was updated
