### ISSUE TITLE
[Feature] [Portfolio] - Make Payout Clear When Looking At Another Person's Portfolio

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#505]
Issue: it is confusing when looking at someone else portfolio that you should look at your own portfolio for potential payout

Feature: Update the card and simplify it to show that you can check out your own portfolio

![image](https://user-images.githubusercontent.com/74615189/135276940-c79c8991-a167-4fb9-98da-b79b2e9d67da.png)

Suggested Solution

"See how much your ideas are earning"

Button "View your portfolio now"

![image](https://user-images.githubusercontent.com/74615189/135277276-34424b50-d9e6-4c6e-9b24-78b1be8236b4.png)

**Comment by graceeguo** [comment]
updated auth cards:
pls click on each component to check the name of the variant for use case
https://www.figma.com/file/pizXCBgqeYUJwn6KP5bagT/Watchlist-and-Ideas?node-id=1022%3A2759

**Comment by stuartjm5** [comment]
Was updated
