### ISSUE TITLE
[Feature] [AIODD] - Standardize Box Sizes

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#508]
Note from user: When building own DD, should be able to expand each section, no matter if there’s no more content, just a snap in place to create even-ness. Slightly OCD in that sense, but it would look very clean and easier to read left side stuff and right side without pieces overlapping left to right

![image](https://user-images.githubusercontent.com/74615189/135278209-57df4cdc-3dd1-4590-8584-034506198848.png)

Solution: Create 2 standard box sizes 
1. Full Size Height
2. Half Size Height

**Comment by graceeguo** [comment]
def agree, would look a lot cleaner
would suggest using the 12 unit system / flexbox

**Comment by Ameria3** [comment]
Following

**Comment by stuartjm5** [comment]
moved to client
