### ISSUE TITLE
[Question] [Portfolio] - How does the Authority Score Work?

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#509]
note: I wanna know more about the authority score because you the viewing metric is a bit misleading if people just post “to the moon” and get views. How does the cash out work? You shouldn’t be able to see comment on ur own profile or user itself unless that’s what your intentions are, this being my portfolio lol.

to do: provide info to Togethearn about Authority Score

![image](https://user-images.githubusercontent.com/74615189/135283269-0192ea17-4212-4b40-bbda-9223b6790dfc.png)

**Comment by graceeguo** [comment]
users can learn more by clicking on the info button -> **should take them to the info/get rewarded page**
here are the suggested changes to make the direction more clear:
left is new, right is current
![image](https://user-images.githubusercontent.com/14366944/135359040-6bd986fa-9b34-48f2-9ef4-c783716449c6.png)
