### ISSUE TITLE
Not getting success reset password mail.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#51]
As a user, when we do reset password flow then after success reset of password user should get mail for the same.

Refer Screencast: http://somup.com/crnFQUDZxJ

**Comment by zhan1634** [comment]
I'm really sorry but I do not understand what this statement means.

**Comment by Ashish8822** [comment]
@zhan1634 I mean to say that, whenever end user go with the forget password flow and after success reset of password the success reset mail should be sent to the concerned user mail id for which he used to login.

If still not clear then let me know.

**Comment by zhan1634** [comment]
Okay to clarify. A user should get an email that says their password has been reset successfully.

**Comment by Ashish8822** [comment]
yes

**Comment by zhan1634** [comment]
Updated in next release
