### ISSUE TITLE
[Feature] [AIODD] - "Performance" Box Format to be updated

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#511]
Note: a little more appealing than just left to right?

Solution: can We look at car design from previous version - before the AIODD?

![image](https://user-images.githubusercontent.com/74615189/135283843-d1a59035-d1b5-454e-8049-63e2b391bb5d.png)

**Comment by graceeguo** [comment]
I would also like the prev grid system to be implemented
but i remember something about responsive components preventing the prev. grid system

**Comment by zhan1634** [comment]
![image](https://user-images.githubusercontent.com/30502801/135500807-5ae29c4a-07eb-4300-b27c-ccd26e12e2ab.png)
