### ISSUE TITLE
Chat function request 

### ISSUE THREAD

**Issue by Ameria3** [Utradea-Inc/utradea-public#512]
I have a chat function ask (in Utradea). I made a comment about 5 or so days ago. I went back into chat and it opened to the newest conversation. Is there anyway to set the chat where it pauses the conversation where you left at? Any conversation can get buried if you have to leave a conversation for a while

**Comment by zhan1634** [comment]
Can you monitor discord / fb / whatsapp to see if this is a standard behavior? Not that I don't agree I can defs timemark it. but just wanna see how the other guys do it.

**Comment by Ameria3** [comment]
Discord timestamps but then almost immediately rolls up to the newest. It’s a pain in the butt scrolling back and finding where I left the conversation

**Comment by stuartjm5** [comment]
Chat was updated
