### ISSUE TITLE
[Feature] [Social Sentiment Dashboard] - Create ability to filter by subreddit

### ISSUE THREAD

**Issue by stuartjm5** [Utradea-Inc/utradea-public#513]
Feedback from user's in Canada is that they can't see trending Canadian tickers because there are not as many mentions relative to the other subreddits. Would like to be able to look at r/canadianinvestor or r/baystreetbets.

**Comment by zhan1634** [comment]
View Stock page instead - there isn't enough volume on reddit to support this.
