### ISSUE TITLE
Library 

### ISSUE THREAD

**Issue by Ameria3** [Utradea-Inc/utradea-public#514]
Can we create a library to house training videos?

**Comment by zhan1634** [comment]
yes.

**Comment by zhan1634** [comment]
can you provide some examples of training videos?

**Comment by Ameria3** [comment]
https://youtube.com/playlist?list=PL5DRGvOVr7fTr7uptk8Ep3Zmlwt-qcY99

**Comment by Ameria3** [comment]
https://youtube.com/playlist?list=PL5DRGvOVr7fRV9yrLg4bUWPD1rWgCcF1p

**Comment by zhan1634** [comment]
Do you have edicational written content as well?

**Comment by Ameria3** [comment]
https://www.togethearn.com/market-basics

I created a site so I have it in a different format as well.

**Comment by stuartjm5** [comment]
We have Utradea youtube channel
