### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by Ameria3** [Utradea-Inc/utradea-public#515]
Is it possible to identify people by a sub group. For instance, basic user, elite user, admin, etc. 
![26B040FE-F184-420B-B1A1-3EAE2685F9AC](https://user-images.githubusercontent.com/91645353/136056214-9feee5c0-81e3-4a69-8bb3-bc4b14fda81e.png)

**Comment by Ameria3** [comment]
Admin is real important because if someone needs help, they need quick access to help

**Comment by stuartjm5** [comment]
users have identifiers
