### ISSUE TITLE
Price Error

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#516]
The Prices on TSX.V and OTC stocks is based off of the last close. My ALPP position (Premium idea on WallStreetWhale) was posted tonight (Oct 19th) when the price should be $4.50/share, however it posted it at yeaterday's (October 18th) close of 5.36.

<img width="879" alt="BUG" src="https://user-images.githubusercontent.com/84204695/138012650-0c91b0b0-fd42-4348-a011-96d73a5ce4c1.png">

**Comment by zhan1634** [comment]
let me take a look at this - I know this to be an issue, it should be updating on the second source, but I'll see why its not

**Comment by stuartjm5** [comment]
moved to client
