### ISSUE TITLE
Beta - Authority Score - Base Pay - Next Pay showing NaN for a new account

### ISSUE THREAD

**Issue by gopala-goyal** [Utradea-Inc/utradea-public#525]
For a new account, the authority score base pay per 1000 views as well as for the 'Next' pay rate is displaying NaN 

![image](https://user-images.githubusercontent.com/64698636/148085310-5364feaa-652f-435e-aab6-4fa1ee8f0a0d.png)

**Comment by zhan1634** [comment]
Fixed in next release
