### ISSUE TITLE
Beta - Authority Score - Positions remain selected if user tries to cancel the Cashout after selection

### ISSUE THREAD

**Issue by gopala-goyal** [Utradea-Inc/utradea-public#526]
On the Authority Score page, when a user clicks on Cashout, after selecting the positions to be cashed out, if the user tries to cancel by re-clicking on the cashout button, the positions remain in the 'Positions to be Cashed Out Bucket'

![image](https://user-images.githubusercontent.com/64698636/148099608-9bba5a2e-6f22-438b-90d4-34b224425b76.png)
![image](https://user-images.githubusercontent.com/64698636/148099637-6697e63e-3d90-4e65-841a-b8d04e6ad9a6.png)
![image](https://user-images.githubusercontent.com/64698636/148099665-56f55fe6-c2aa-4653-a622-d892829d88a1.png)

The positions should be removed from the bucket if the user tries to cancel the cashout process

**Comment by zhan1634** [comment]
Does not deselect but I've removed the white box for now.
