### ISSUE TITLE
Mobile app issue: Images get cut from the right side

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#529]
In the mobile app, we can't see the whole image in any article. The images always get cut from the right side. See both comparison mobile vs desktop
![Desktop 2](https://user-images.githubusercontent.com/95775238/148607012-9b6ca89d-8de6-4f6b-88d6-88e5f4877e86.JPG)
![Desktop](https://user-images.githubusercontent.com/95775238/148607015-290a77ee-e67c-42c3-b2ec-bfb02ddc1908.JPG)
![Mobile issue 2](https://user-images.githubusercontent.com/95775238/148607017-aa723a44-cb4e-48c8-b099-414ed87049f4.jpg)
![Mobile issue](https://user-images.githubusercontent.com/95775238/148607020-7bc02fb2-2816-4119-b190-0fa374f5cdd9.jpg)
.

**Comment by stuartjm5** [comment]
Moved to client
