### ISSUE TITLE
Only the Logo should be clickable not the space below logo.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#53]
As a user, when we click on the space which is below the logo then it takes you to the landing page but here only logo should be redirected to the LP not the space. 

Please check, I know it is a quite low priority but still look into it and let me know the expected behavior as per you.

Refer Screencast: http://somup.com/crnF60DZza

**Comment by zhan1634** [comment]
This is not a major issue as the majority of the time this will not happen. In addition, this may be removed in a later version.
