### ISSUE TITLE
Ipad app: Images get weird overlap

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#530]
In the Ipad app,  images get some weird overlap for Digital Turbine(APPS). This makes part of the article impossible to read. Check Ipad vs Desktop comparison. 
![Ipad issue](https://user-images.githubusercontent.com/95775238/148607595-ad71f0d1-4bbc-4c13-aa8b-21c55b06d51e.jpg)
![Desktop](https://user-images.githubusercontent.com/95775238/148607687-3df75195-fe7c-4e6d-9104-1fedf3df1372.JPG)

**Comment by zhan1634** [comment]
Fixed in the next release
