### ISSUE TITLE
Photo Bug

### ISSUE THREAD

**Issue by PAmandaT96** [Utradea-Inc/utradea-public#532]
<img width="349" alt="Screen Shot 2022-01-10 at 11 42 07 AM" src="https://user-images.githubusercontent.com/97464711/148803756-6f12b581-308f-4a9e-b87b-edfff2548605.png">

**Comment by Pravenan** [comment]
<img width="366" alt="Screen Shot 2022-01-10 at 11 54 36 AM" src="https://user-images.githubusercontent.com/97464598/148807304-59a25fb5-33f1-403f-b2cf-2d7cf4b88935.png">

**Comment by graceeguo** [comment]
[parker.docx](https://github.com/Utradea-Inc/utradea-public/files/7840960/parker.docx)
