### ISSUE TITLE
Photo Bug

### ISSUE THREAD

**Issue by gopala-goyal** [Utradea-Inc/utradea-public#533]
![IMG-20211120-WA0060](https://user-images.githubusercontent.com/64698636/148804034-5b0788f0-f23a-4afe-9c5a-f71db803514c.jpg)

**Comment by graceeguo** [comment]
would suggest submitting a clearer picture though!

[gopala.docx](https://github.com/Utradea-Inc/utradea-public/files/7840963/gopala.docx)
