### ISSUE TITLE
Photo Bug

### ISSUE THREAD

**Issue by Pravenan** [Utradea-Inc/utradea-public#537]
<img width="468" alt="Screen Shot 2022-01-10 at 12 29 09 PM" src="https://user-images.githubusercontent.com/97464598/148811067-f4fac89e-022a-4e6c-8e86-71c2921d1085.png">

**Comment by graceeguo** [comment]
would suggest using a picture with a less busy background!
i c u in mtl tho

[prav.docx](https://github.com/Utradea-Inc/utradea-public/files/7840988/prav.docx)

**Comment by Pravenan** [comment]
![Uploading Screen Shot 2022-01-10 at 1.50.37 PM.png…]()

**Comment by Pravenan** [comment]
<img width="466" alt="Screen Shot 2022-01-10 at 1 50 37 PM" src="https://user-images.githubusercontent.com/97464598/148822126-4bc25058-e2d3-4821-a2e9-392828a3e640.png">
