### ISSUE TITLE
[FEATURE] Add a reference link to manually scouted ideas

### ISSUE THREAD

**Issue by OmarAtUtradea** [Utradea-Inc/utradea-public#539]
Scouting posts that have been scraped by the website leads to a link to the original post, but if it's manually scouted (ie. fields are filled in by hand) the "original post" link points to https://www.reddit.com/r//comments//.

A field to enter original link would be helpful.

![Screen Shot 2022-01-13 at 10 44 19 AM](https://user-images.githubusercontent.com/97464812/149361964-0f8e81e8-746a-4369-8802-febac25d8aba.png)
![Screen Shot 2022-01-13 at 10 44 30 AM](https://user-images.githubusercontent.com/97464812/149362013-95e78829-d718-4c9d-87c4-cdbf244b7d65.png)

**Comment by zhan1634** [comment]
Reference links are there, if the original post doesn't provide one or if it breaks or gets moved I do not have a backup link unfortunately.
