### ISSUE TITLE
Actual value is getting converted

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#54]
Actual value is getting converted in some other numerical .In the post idea section when we move to quick intro section and type 123 or 456 or 789  it gets converted into 100 and not allowing more than 3 digits . But when we type 00000000000000 , it accept this format

Video: http://somup.com/crnF6HDZBa

**Comment by zhan1634** [comment]
This has been resolved and deployed to beta as of Feb 24, 2020 11:59PM EST.
