### ISSUE TITLE
[BUG] Typo on Financial Statements on DD Dashboard

### ISSUE THREAD

**Issue by OmarAtUtradea** [Utradea-Inc/utradea-public#540]
![Screen Shot 2022-01-25 at 12 01 15 PM](https://user-images.githubusercontent.com/97464812/151023757-90b06a4b-09d4-4790-9d76-37bc9f416eb5.png)
Long Term Investments has two S's under the Balance Sheet portion of the financials

**Comment by zhan1634** [comment]
Fixed in latest release.
