### ISSUE TITLE
Crypto Ticker from SSD

### ISSUE THREAD

**Issue by PAmandaT96** [Utradea-Inc/utradea-public#541]
When you click on crypto tickers to view their analysis dashboard the page opens and then says "Sorry, It seems like we don't have this ticker in our database. Try another ticker!"

 But if you look the tickers up on the platform they display perfectly fine. 

SSD Page 
<img width="1011" alt="Screen Shot 2022-01-27 at 9 59 12 AM" src="https://user-images.githubusercontent.com/97464711/151384750-5653e0fc-b9b9-47fa-a96d-66fa941b2844.png">

"Sorry..." page 
<img width="1069" alt="Screen Shot 2022-01-27 at 9 55 29 AM" src="https://user-images.githubusercontent.com/97464711/151383652-7bc6b4ee-af8a-4a71-bd2f-19153c945aa9.png">

Ticker Analysis Dashboard
<img width="1024" alt="Screen Shot 2022-01-27 at 10 02 32 AM" src="https://user-images.githubusercontent.com/97464711/151384982-a92f63c7-93df-4464-8945-ab2aa781f3d2.png">

**Comment by zhan1634** [comment]
Moved to utradea-client to resolve. Will be released in next update.
