### ISSUE TITLE
[Ideas] Card overlap on right corners of premium border

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#542]
<img width="626" alt="Screen Shot 2022-02-10 at 5 05 44 PM" src="https://user-images.githubusercontent.com/90401001/153504889-880d20a6-9a29-4df8-9d44-b123c1140de3.png">
<img width="86" alt="Screen Shot 2022-02-10 at 5 07 28 PM" src="https://user-images.githubusercontent.com/90401001/153504899-99128c43-1d00-4885-a8fa-958b1a47a3d9.png">

Card overlaps the premium yellow border on both right corners

**Comment by zhan1634** [comment]
No longer relevant
