### ISSUE TITLE
[Feed] Icons too high on each button

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#543]
![Screenshot (309)_LI](https://user-images.githubusercontent.com/82605301/153505574-3d18a642-763f-4e3a-a421-5df1c12297ea.jpg)

On the right side of the feed page, there's an icon accompanying text in each button
The icons seem like they're placed too high though; the distance above and below the icons aren't the same (see image for clarification) + center of the icons don't line up with the center of the text
please line them up vertically with the center of the button + the text, thank you~

**Comment by zhan1634** [comment]
No longer relevant in latest release
