### ISSUE TITLE
[Feed] Blurry Premium icon + text

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#544]
<img width="1318" alt="Screen Shot 2022-02-10 at 6 00 18 PM" src="https://user-images.githubusercontent.com/90401001/153511232-b9cec931-7c0c-44d1-92d4-a3b60197b771.png">

<img width="1076" alt="Screen Shot 2022-02-10 at 6 01 32 PM" src="https://user-images.githubusercontent.com/90401001/153511276-1d9f6314-6a33-41f5-8e35-04b502b20a29.png">

Text "Utradea premium" and icon is blurry, need to increase pic quality/resolution

**Comment by zhan1634** [comment]
Premium overlay removed for golden ideas in latest release
