### ISSUE TITLE
[Feed] "More" button hitbox too small

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#545]
![Screenshot (315)_LI](https://user-images.githubusercontent.com/82605301/154095843-9d823333-a015-442c-8f49-8ee8287581e7.jpg)

Image is when the "more" button is being pressed; the orange highlighted hitbox shows that it is too small
Please make it larger like the "less" button hitbox shown below:

![Screenshot (315)](https://user-images.githubusercontent.com/82605301/154095521-8cb6b67a-bf05-479f-bf1a-49cd61949e6c.png)

**Comment by zhan1634** [comment]
Fixed in latest release
