### ISSUE TITLE
[Feed] Earnings report buttons not aligned

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#546]
two issues:
a. occurred spelled incorrectly
b. "more" and "less" buttons on earnings report not aligned correctly with voume alert buttons 

- "less" button is too long on the left
- "more" button is shifted too much towards the right

![Screenshot (317)_LI](https://user-images.githubusercontent.com/82605301/154098085-299ec3d1-6fe2-476c-abfa-d09f26f34a41.jpg)

![Screenshot (318)_LI](https://user-images.githubusercontent.com/82605301/154103379-9b5f8bda-6fb7-4103-a650-ef71407128af.jpg)

**Comment by zhan1634** [comment]
fixed in latest release
