### ISSUE TITLE
[Feed] Analyst downgrade text placement

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#547]
![Screenshot (320)_LI](https://user-images.githubusercontent.com/82605301/154110997-5838bc42-712f-45e0-9b1b-cf06353868af.jpg)

a. company name text is placed too high; make the text smaller or place it lower so it's more low than the start of the container next to it

b. also, shift the company name text to the right a little more, the container below it shouldn't be aligned with the start of the text

see figma for reference:
![Screenshot (320)](https://user-images.githubusercontent.com/82605301/154109697-b9da3f5e-6d8a-4eb6-a735-81225a893071.png)

**Comment by zhan1634** [comment]
Fixed in the next release
