### ISSUE TITLE
[Feed] Price alert text placement

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#548]
![Screenshot (321)_LI](https://user-images.githubusercontent.com/82605301/154112711-a12a4ca9-a48e-45fa-8bf7-259dc73f768c.jpg)

a. occurred spelled incorrectly
b. alignment for text "occurred Feb 15th, 9am" should be flipped (more empty space on the right than on the left)

**Comment by sissizhu12** [comment]
note: occurred is spelled incorrectly on the beta website for mobile as well, please fix that!

**Comment by zhan1634** [comment]
anchored to the left, occurred text fixed
