### ISSUE TITLE
[Mobile][Feed] Analyst Maintain card text cut off

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#549]
![IMG_1113](https://user-images.githubusercontent.com/82605301/154560541-628d9242-3042-4705-9212-0788a8e3d8a6.jpg)

Grey "Buy" text for Analyst Maintain cards is cut off when user clicks on "more" details tab
Maybe move the arrows and green "buy" text slightly more to the right (arrow doesn't seem like it's aligned in the middle)

**Comment by zhan1634** [comment]
Fixed.
