### ISSUE TITLE
[App] [SEC Dashboard] Document doesn't fully vertically scroll

### ISSUE THREAD

**Issue by sissizhu12** [Utradea-Inc/utradea-public#551]
When clicking into the SEC dashboard, then a company in the feed, then on the "full view" button
The filing document that gets opened doesn't scroll vertically all the way to the bottom when it should, it gets stuck before the end of the document  (see screenshot for where it gets stuck)

![image](https://user-images.githubusercontent.com/82605301/156195838-443d9631-421d-4897-99d0-6304e90686f6.png)

**Comment by stuartjm5** [comment]
Moved to client
