### ISSUE TITLE
[App][Prices] CTA button needed for Ideas and Watchlist card

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#553]
Add a call to action button (i.e. Write your idea) for Ideas card: 
![Screenshot_20220303-125543_Utradea (1)](https://user-images.githubusercontent.com/90401001/156624985-181324f1-31ea-4f97-bad7-e71fb652e25d.jpg)

Add call to action button for watchlist card (i.e. Search for Stocks):
![Screenshot_20220303-125551_Utradea (1)](https://user-images.githubusercontent.com/90401001/156625051-40ce5301-43aa-4d0e-a9b8-fb46d84dc003.jpg)

@zhan1634

**Comment by zhan1634** [comment]
Updated in the latest release
