### ISSUE TITLE
[App][Ideas] Text under Sec and Sentiment icons too close together

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#554]
![SmartSelect_20220303-130434_Utradea_2](https://user-images.githubusercontent.com/90401001/156625626-d9bbe50e-b52c-429c-b414-86db397d5f4f.jpg)

Space between Sec filing and sentiment is too limited, hard to read. Consider putting Filing on the second line for readability. 

@zhan1634

**Comment by zhan1634** [comment]
Fixed in next release
