### ISSUE TITLE
[App][Saved] CTA button (Go to Feed) needed for empty saved list 

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#555]
If saved list is empty, include a button (Go to Feed)

![SmartSelect_20220303-132135_Utradea](https://user-images.githubusercontent.com/90401001/156629139-af9205c4-a94f-43d2-8ccc-8640372aa3da.jpg)

@zhan1634

**Comment by zhan1634** [comment]
Fixed in latest release
