### ISSUE TITLE
[App][Feed] Report Idea inconsistent between [Feed] and [Idea] 

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#556]
Reported an idea, then unreported it on the feed: 
![SmartSelect_20220303-132741_Utradea](https://user-images.githubusercontent.com/90401001/156629618-1a835c93-7fab-4789-8eda-e0a54230e77b.jpg)

However when idea is clicked, it still shows that it is reported: 
![SmartSelect_20220303-132755_Utradea](https://user-images.githubusercontent.com/90401001/156629736-89de305d-f675-4d06-9e35-66c3926100c8.jpg)

@zhan1634

**Comment by RajnishKatharotiya** [comment]
@zhan1634 Resolved
