### ISSUE TITLE
[App][Saved] Same icon used for Polls and Tools

### ISSUE THREAD

**Issue by FaithD186** [Utradea-Inc/utradea-public#557]
Same icon used for polls and tools: 

![SmartSelect_20220303-132343_Utradea (2)](https://user-images.githubusercontent.com/90401001/156630750-6c342b4d-770b-4b5d-9691-4f520b9ebd1b.jpg)

Should change icon for polls. 

@graceeguo @zhan1634

**Comment by zhan1634** [comment]
@graceeguo
