### ISSUE TITLE
Blog Formatting

### ISSUE THREAD

**Issue by PAmandaT96** [Utradea-Inc/utradea-public#558]
H3 for blogs needs to be adjusted so it's differentiated from the paragraphs

**Comment by zhan1634** [comment]
Do you know what you want for H3? This styling is used for the same as positions.

**Comment by PAmandaT96** [comment]
I'm not sure- I just noticed when I used H3 on the blogs it shows up as regular body font and style rather than a heading.

**Comment by zhan1634** [comment]
Fixed in the next release
