### ISSUE TITLE
Beta version error with watchlist

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#559]
@zhan1634 
In the full watchlist(with 10 holdings) after hitting edit, If you delete some holdings and try to add other holdings in the same edit no matter how many holdings you have in the list, it still gives the error that you don't have enough space in the watchlist. 

Here I have 3 holdings and if I try to add more holdings, it throws an error "Please ensure your watchlist has enough spaces"

Contact me if you have any questions about this error. Here I am attaching the screenshot.
![Issue with watchlist](https://user-images.githubusercontent.com/95775238/160012514-09876fa1-59f3-4f38-867a-c5e8ca6ac161.JPG)

**Comment by stuartjm5** [comment]
moved to Client
