### ISSUE TITLE
Color of validation appearing incorrect.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#56]
As a user, when we try to enter wrong password and click on submit button then the color is appearing green instead of red. Please have a look: 
![image](https://user-images.githubusercontent.com/79117207/108476207-c8e58a00-72b7-11eb-8508-cbec196ce336.png)

**Comment by zhan1634** [comment]
![image](https://user-images.githubusercontent.com/30502801/109077292-e5276380-76c9-11eb-9694-3a3ac239ce5b.png)

Please provide reproduction steps.

**Comment by Ashish8822** [comment]
@zhan1634 Its fixed now, you can close this.

**Comment by Ashish8822** [comment]
yes  working fine now
