### ISSUE TITLE
Shares Outstanding NLP error

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#563]
When parsing my TSLA position, it stated that TSLA's shares outstanding was 1**M** when in fact it is more like 1.134**B**

**Comment by zhan1634** [comment]
![Screen Shot 2022-04-12 at 9 38 58 PM](https://user-images.githubusercontent.com/30502801/163082023-b80d72b4-b29e-4727-9c4e-81dc68249aa0.png)

I think you are using the main one, not the diluted amount.
