### ISSUE TITLE
Position Upload - Parsing issues

### ISSUE THREAD

**Issue by gopala-goyal** [Utradea-Inc/utradea-public#565]
Steps to Replicate - 

Step 1- Paste the template on the Position upload page

![image](https://user-images.githubusercontent.com/64698636/162786488-a60fa1f4-5e23-4a98-a30d-a74f7ba8d824.png)

Step 2 - Parse the content by selecting the text

![image](https://user-images.githubusercontent.com/64698636/162786561-a28012fe-406d-4fc2-8f83-ae73857bb4b2.png)

Step 3 - Compare the fields and their corresponding values

Issue: the stock grade values are incorrect - see the below screenshot:

![image](https://user-images.githubusercontent.com/64698636/162786611-623cd923-6cec-4671-a29c-fe1a3c610113.png)
![image](https://user-images.githubusercontent.com/64698636/162786643-68629993-03cd-4906-b88f-13e4fa287f6a.png)

Step 4 - When I try to change the field in the text box by selecting the text [stock_grade_previousGrade] and then selecting the field from the sidebar (from Alerts), the value gets corrected

![image](https://user-images.githubusercontent.com/64698636/162786677-11e32fe7-e9d0-45b1-aa3b-1da5c2b6bac0.png)

Issue 2 - When you try to parse the text in the text box again, income statement values stop getting parsed.

![image](https://user-images.githubusercontent.com/64698636/162786705-26f499d0-5aa6-4d5c-98df-8a75c92e75b8.png)

**Comment by zhan1634** [comment]
Updated in the next release
