### ISSUE TITLE
Position Upload - Sidebar - Company Description is incomplete

### ISSUE THREAD

**Issue by gopala-goyal** [Utradea-Inc/utradea-public#566]
What happened?
When I tried to put Company Description into the textbox for any position upload, after selecting the text, the company description is not rendered completely. It shows an incomplete sentence with '...' at the end.

Steps to replicate:
Step 1 - Add the field [company_description] into the textbox for position upload
Step 2 - Select the text and check the parsed sentence

Result:

![image](https://user-images.githubusercontent.com/64698636/162787586-62229a2a-0755-49ae-9211-5744f3df6b8f.png)

![image](https://user-images.githubusercontent.com/64698636/162787625-1f7e9c59-6745-44fb-afaf-09caebbace07.png)

**Comment by zhan1634** [comment]
Fixed in next release
