### ISSUE TITLE
Issue with fiscal year notation

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#568]
@zhan1634 @stuartjm5 
Utradea platform denotes the fiscal year as a normal number.

I.e. It rights the 2022 fiscal year as 2,022 instead of 2022 so in terms of writing, we write Q-1-2022, not Q-1-2,022. 

Please see the attached screenshot for more info

![Issue with Fiscal year notation](https://user-images.githubusercontent.com/95775238/164065115-3a3b4640-145d-4beb-ae67-4d22e4834d22.JPG)

**Comment by stuartjm5** [comment]
moved to client
