### ISSUE TITLE
Sentences field overlap the writing area

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#569]
Some of the right portions are not visible as the sentence tab overlaps the writing area while you write ideas/ sentences. This makes it very hard to read things while writing in that area that can be optimized. See attached screenshot for reference.
@zhan1634 @stuartjm5 
![image](https://user-images.githubusercontent.com/95775238/168261361-61febf94-985d-4051-a139-f3fe4b90cf8f.png)

**Comment by zhan1634** [comment]
Fixed in next release.
