### ISSUE TITLE
Validation error is not specified in Update Profile section.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#57]
As a user, if I am updating my profile and entered all incorrect data then how user come to know which field has incorrect data. For instance: Entered wrong First Name, Last Name, Username, Email Id and the current password of the user all are incorrect. It should throw specified validation error for the wrong entered field.

Refer Screencast: http://somup.com/crnqjZDOp5

**Comment by zhan1634** [comment]
We may change the entire user experience of this section. TBD.
