### ISSUE TITLE
Maybe we should attach $ sign to all the price changes/ 52 weeks high/low. 

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#570]
I believe we should attach a $ sign to all the price changes/ 52 weeks low and high. 
I.e Instead of regular market change we can include a market change in $s. Here I did put the $ sign in front of the  [price_regularMarketChange] to parse the sentence. The parsed sentence looks a little odd as we generally right the negative change -$5 not $-5.  See attached screenshot for more information. @zhan1634 @stuartjm5 
![image](https://user-images.githubusercontent.com/95775238/168263754-78e7f9cd-3aa8-4024-9748-433bb51de2da.png)

**Comment by zhan1634** [comment]
This depends on the user - with $ you will also have currency for now, we can leave it out which allows the user to customize as they wish.
