### ISSUE TITLE
Delete button error in NLP sentences non-reviewed tab

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#571]
If we try to delete some sentences from the non-reviewed tab by using the delete button the portal gives a message 'sentence saved successfully', Instead of saying 'sentence saved successfully' it should say 'Sentence deleted successfully' as a message down there. See the screenshot for more info.
@zhan1634 @stuartjm5 
![image](https://user-images.githubusercontent.com/95775238/168266670-d49fa54c-0457-48ca-a4ac-7cad2fcebe07.png)

**Comment by zhan1634** [comment]
Updated in the next release
