### ISSUE TITLE
Modify sentence option does not work for the reviewed sentences

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#572]
In the reviewed and non-reviewed tab the modify sentence option works for only 1st sentence on each page. Even after editing/modifying the sentence, it turns back to the original sentence once I refresh it. 

Also, the modification/editing feature does not work for the sentences that come after the 1st sentence on each page.  Refer to the screenshot for more info. 
@stuartjm5 @zhan1634 
![image](https://user-images.githubusercontent.com/95775238/168901970-8fea84dd-c2b5-4bb1-8ced-1ab128003244.png)

**Comment by zhan1634** [comment]
Fixed in the next release
