### ISSUE TITLE
G&A expenses error

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#574]
The G&A expense for Apple stock is not 0 but this gives G&A expense result 0. 
@zhan1634 @stuartjm5 
![image](https://user-images.githubusercontent.com/95775238/170805933-3c91d00c-a191-4fe8-a793-c6671a03b069.png)

**Comment by zhan1634** [comment]
Based on AAPL's report and filing they do not break down SG&A further to G&A - so use the SG&A one. This has been verified.
