### ISSUE TITLE
NLP sentences are not loading

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#577]
The predefined fields in most of the sentences are not loading. They are giving an error message. Please see the attached screenshot for more info. 
@zhan1634 
![NLP sentences loading error](https://user-images.githubusercontent.com/95775238/172284367-ea8cfc51-dd29-484e-bc8f-46dcac35f9f1.JPG)

**Comment by zhan1634** [comment]
Specify a ticker
