### ISSUE TITLE
Scroller is not required in this page.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#58]
As a user, when I click on the sidebar logo then there is a scroller on the left. What's the purpose of that scroller?

Screencast: http://somup.com/crnqjkDOCU

**Comment by zhan1634** [comment]
All scrollers have been disabled when tutorials are in action. This will be effective on BETA. This has been resolved and deployed to beta as of Feb 24, 2020 11:59PM EST.
