### ISSUE TITLE
Price to Equity ratio addition under ratios tab

### ISSUE THREAD

**Issue by ugajjar99** [Utradea-Inc/utradea-public#583]
We have a Price to Equity ratio under peers--> valuation but don't have a standalone Price to Equity ratio for a particular company. So in case, we want to compare the Price to Equity of any company to its peers first we need to have a price-to-equity ratio for the company we are writing an article about. Please see attached screenshots for more info @stuartjm5 @zhan1634 
![image](https://user-images.githubusercontent.com/95775238/178309525-49ad9203-c52e-460d-8e7d-803da1117da2.png)
![image](https://user-images.githubusercontent.com/95775238/178309696-630f0493-b7eb-4819-afa4-889360db9819.png)

**Comment by zhan1634** [comment]
This is PE Ratio under Key Stats
