### ISSUE TITLE
No notification for user that invite link has been copied 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#60]
Under Profile tab, When user click on invite button user don't see any message or popup that link has been copied.
Video : http://somup.com/crnqodDtYJ

**Comment by zhan1634** [comment]
Can you specify the OS and system, this appears to be working fine on my end. Please provide reproduction steps. 

![image](https://user-images.githubusercontent.com/30502801/109074539-e0f94700-76c5-11eb-907c-9aa09c2696bc.png)

**Comment by Ashish8822** [comment]
I am using windows 10 and tested on google chrome

**Comment by zhan1634** [comment]
This has been resolved and deployed to beta as of Feb 25, 2020 11:59PM EST. This is with another bug. This is because the screen size is rather small so it displays upwards.
