### ISSUE TITLE
User don't get notification to switch to mobile version

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#61]
When user login and zoom for the first time to 150% a notification popup saying either to switch to mobile version or to stay here . When user select stay here and then zoom out to normal 100% and after that again zoom in to 150% no notification popup . User should be asked every time when the zoom to 150% whether they want to stay to this website or switch to mobile version.

Video : http://somup.com/crnqo9Dt3i

**Comment by zhan1634** [comment]
Although this is the case, as a user, the reason it will prompt you is that in a session you will typically switch to one view and stay with one view. The constant pestering of whether or not to stay will become another bug later on.

**Comment by Ashish8822** [comment]
Ok I agree with you . But suppose for better visibility he wanted to zoom to 150%, what if a user by mistake clicked on mobile view and want to go back to normal screen-size and he is in the middle of posting an idea . So in this case now he has to end the session completely by closing the browser and then start all over again.
