### ISSUE TITLE
Nott getting access or deny privacy policy for personal information,When user try to login with facebook.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#65]
When user login with facebook then it should ask access or deny your personal information of facebook.

STR: 
1. Click on facebook icon to login with facebook.
2. It should ask privacy policy access just after login from facebook.

Refer Screencast: http://somup.com/crnT1wDBFn

**Comment by zhan1634** [comment]
By using the site you agree to the privacy policy and terms and conditions. Although this is an issue - the user by connecting their social account agrees to the conditions. This is how it is implemented on other websites as well.
