### ISSUE TITLE
After login from facebook, update profile fields are enable to edit.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#66]
As a user, when i am login with facebook, how user get access to change the profile details of facebook from utradea application and after entered all the fields correctly, it throwing validation for incorrect password though the password is correct.

1. Login with facebook.
2. click on settings icon.
3. fill all the details and try to change it.
4. 0bserve the result.

Refer screencast: http://somup.com/crnT1aDBF2

**Comment by zhan1634** [comment]
In this case did you set up a password to begin with?

**Comment by Ashish8822** [comment]
@zhan1634 I am not getting you could you elaborate it?
