### ISSUE TITLE
Back button not working in sign in page

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#67]
Steps to reproduce:
1. Go to https://beta.utradea.com/session/signup
2. Click on sign-in here
3. Now as the sign-in page opens click on back button and it will go back to registration page
4. Again click on sign-in here and navigate to sign-in page
5. click on utradea logo 2-3 times
6. Observe the back button is not working.

Browser used Firefox, Chrome
Please refer to video:
Video: http://somup.com/crntjFDCkh

**Comment by zhan1634** [comment]
Click back button a few more times. You've clicked on the logo multiple times so you've been redirected to the sign in page multiple times. This is not a bug this is just poor user testing.
