### ISSUE TITLE
Allowing user to register with any invalid email domain

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#68]
Steps to reproduce : 
1. Go to https://beta.utradea.com/session/signup
2. Enter all the required details and in the place of email enter any invalid domain of email suppose ashish@456.com
3. Click on register
4. Observe the result
Browser used Google chrome and firefox
For your reference please see the video
Video : http://somup.com/crnt2sDCMo

**Comment by Ashish8822** [comment]
![image](https://user-images.githubusercontent.com/79117207/109382420-59e6e180-7906-11eb-9054-67be900418b5.png)

**Comment by zhan1634** [comment]
Email verification will come in in the future to prevent this from happening.

**Comment by zhan1634** [comment]
Updated in next email validation release
