### ISSUE TITLE
Portfolio page - Issue when taking desktop full screen and snapping window to half/part of display

### ISSUE THREAD

**Issue by leiron-james** [Utradea-Inc/utradea-public#7]
Seems like there is an issue with the page's ability to reactively switch from desktop full screen to half screen view. The switch from browser link to mobile link seems to not adapt properly. This is likely an issue to other Utradea pages too.

![image](https://user-images.githubusercontent.com/78940042/107908065-304fb280-6f23-11eb-939c-2c514d50ade3.png)

**Comment by zhan1634** [comment]
![image](https://user-images.githubusercontent.com/30502801/108004720-950f1980-6fc4-11eb-9c1a-603fcdae3ed0.png)
#

It seems to be working fine on my end. Can we further investigate this?

**Comment by leiron-james** [comment]
Yes we can. I think the latest release resolved this for the portfolio page. However to post an idea, it doesn't seem to work. Let me know if you can replicate this.

![image](https://user-images.githubusercontent.com/78940042/108079338-b6abe780-703c-11eb-9a95-6f187a8803fa.png)
