### ISSUE TITLE
Validation error is not specified in Signup page.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#70]
STR: 
1. Enter all the correct data in SignUp Page.
2. Enter Invalid data in Password field
3. Hit "Enter Platform" button
4. Observe the validation error.

Note: The validation error should specified with the field so user can easily understand on which fields need to be corrected.
 This issue has been raised because the validation should mention the correction field i.e., "Password" & "Confirm Password"
Refer Screencast: http://somup.com/crnt2bDC7g

**Comment by zhan1634** [comment]
Resolved in next update.
