### ISSUE TITLE
After Signup the user should redirect to the login page to login with new signup user.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#71]
STR: 
1. Hit the URL.
2. Fill all the details
3. Hit the "Enter Platform" button.
4. Observe the result.

Expected result: 
After signup user should redirect to the sign in page to sign in with newly created user.

Actual Result: After Signup user is logged in and redirected to the login page.

Screencast: http://somup.com/crntouDCLs

**Comment by zhan1634** [comment]
Why should they be redirected to the sign in page? Why? You provided your password, login details already, if it is valid, we use it to sign you in. This sounds like an additional step that does not need to happen.
