### ISSUE TITLE
After login with facebook, incorrect data are showing in update profile settings.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#72]
STR:
1. login with facebook.
2. go to settings
3.  click on update profile settings.
4. check the user details.

Refer Screencast: http://somup.com/crntozDCNl

**Comment by zhan1634** [comment]
"Incorrect data" is not good for debugging. Please specify repo steps, and specify what the data should be. If in Facebook you do not authenticate or provide the valid email, a default one will be generated and you will have the option to update it if you'd like.

**Comment by Ashish8822** [comment]
@zhan1634 After login with facebook, why we need default user info. Don't think it would be a quite confusing for a user. 
As per me, after login with facebook user gets the same details whatever entered in facebook. Like username, F name, L name and the email Id and all the fields should be disable and should provide info icon which say "You are logged in with a facebook and you can't update the information which is fetched from facebook, its against privacy policy".

After all it's my perception on this and its all up to you. Does this make sense to you or not, you can go with that.

**Comment by zhan1634** [comment]
So, in the future you can actually connect more accounts like Google, so you do need default fields. Let's say for example, I created an account with Utradea and I deactivated my facebook after 2 years.... what happens? Does my Utradea account not work anymore? From a process perspective, it makes sense. The default first name and last name should come through, are you seeing something different? There is an issue with email coming through based on the user's privacy policy with Facebook not with utradea.
