### ISSUE TITLE
Able to reset the password after login with facebook.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#73]
STR: 
1. Hit the URL
2. Login with facebook.
3. Click on setting
4. Click update profile setting.
5. Click on reset button on the password field.

Note: How any user can reset their password which is login with facebook. Does this make any sense?

Refer Screencast: http://somup.com/crntDwDC9i

**Comment by zhan1634** [comment]
Given that you logged in with facebook, you "CAN" technically reset your password to the email on file. If you'd like to have the password set to your email, please update your email. This is a perfectly valid response on other websites as well. Given you authenticated with a social media - you can reset your email to the one on file. If you registered facebook with xxx@gmail.com, it will be sent there. HOWEVER, if you did not provide access a default one will be given.
