### ISSUE TITLE
Getting error while login with facebook.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#74]
STR: 
1. Click on Login with facebook.
2. Click on setting
3. Click on update profile settings
4. Click on disconnect button.
5. click on connect button from the same.
6. Observe the result.

Screencast: http://somup.com/crntbVDCRG

**Comment by zhan1634** [comment]
Sorry I switched to development mode for a bit. Please test again.

**Comment by Ashish8822** [comment]
@zhan1634 Its persisting, please have a look: http://somup.com/creVhqDELR

And one more question: After login with facebook, if user disconnect it from update profile setting then that user should logged out or stay logged in?

**Comment by zhan1634** [comment]
They can stay logged in because they have an account created with FB. 

Can you refresh your cookies and cache. This should not be an issue. I double checked on my end as well. Try another browser

**Comment by Ashish8822** [comment]
@zhan1634 I had tried this in incognito mode, there also need to clear the cache or cookies?

**Comment by Ashish8822** [comment]
@zhan1634 Hey, I have checked the same in two different browser as well as two different system to just crosschecked the issue and getting the same error at both place.
STR:
1. Logged in with facebook.
2. Click on settings.
3. Click on update profile setting.
4. Click on disconnect button.
5. Do hard refresh of the page.
6. And try to connect again.
7. Observe the behavior.
