### ISSUE TITLE
User gets logged out after clicking on any active ideas and then clicking on price when posted

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#78]
Steps to reproduce :
1. Go to https://beta.utradea.com/session/signin.
2. login to your account.
3. Under portfolio tab go to ideas section
4. Scroll down to active ideas.
5. click and open any active ideas
6. After opening any active idea click on top where written " price when posted" . 
7. Observe

Actual result: Page gets logged out.
Expected result : Page should not log-out.
Please refer to video : http://somup.com/creVfuDE7p

Note browser used : Firefox , Edge , Chrome

**Comment by zhan1634** [comment]
Utradea was implementing a new authentication framework, this has now been fixed.
