### ISSUE TITLE
Icon gets overlapped and content hides under the left menu tab when zoomed to 125%

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#79]
Steps to reproduce
1. Go to https://beta.utradea.com/session/signin.
2. Login to your account
3. Click on zoom button up to 125-150%
4. See the extreme left menu icons and the contents gets hidden under that tab.

Actual result : Icons get overlapped to each other and contents get hidden under menu after zooming
Expected result: Icons should stay on its place and content also and should not be overlapped 

For reference please see screen video :  http://somup.com/creVhVDEM7

**Comment by zhan1634** [comment]
There's a lot of zoom issues, my question is why would you zoom that close in the first place? Most browsers will have issues.

**Comment by Ashish8822** [comment]
Have you tried zooming to upto 300% to other website ?? try zooming to 300% on facebook.com or any website. all the icons would be stick to its place and no contents will get hidden below any icon . 
Have a look.  
![image](https://user-images.githubusercontent.com/79117207/109615051-6dd65180-7b59-11eb-9dbe-464abb66d17d.png)
