### ISSUE TITLE
Check possibility sign in with email use autocomplite

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#8]
Android 8.1 Chrome

Steps of reproduce
1.go to https://beta.utradea.com/session/signup
2. Click on link Already have an account? Sign in here
3.Add email and click autocomplite email from your browser

**Actual result** filling field of email
**Expected result** Incorrect displayed field of email |  

https://prnt.sc/y1tez8

**Comment by nonameuser2019** [comment]
The same problem when I can filling any field to use autocompleate on Android app
![image](https://user-images.githubusercontent.com/52506727/107987902-90a02c00-6fd7-11eb-86d2-e530922dc26d.png)

**Comment by zhan1634** [comment]
I'm not sure what this is supposed to mean. What does the incorrect displayed field of email mean? You can sign in with both username and email.
