### ISSUE TITLE
User is able to see the profile page for few seconds after hitting URL.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#80]
STR: 
1. Clear all the cache and cookies data.
2. Hit the URL: beta.utradea.com
3. Observe the screen.

Note: After hitting the URL, user is able to see the profile page for few seconds and then it's automatically logged out.

Tested in: Firefox, Edge and Chrome (Incognito mode)

Refer Screencast:
http://somup.com/creV1pDES6

**Comment by zhan1634** [comment]
Utradea has been implementing a new authentication framework, this has now been fixed.

**Comment by Ashish8822** [comment]
This issue is still there . Please have a look http://somup.com/crenIgDJI8
