### ISSUE TITLE
User gets logged-out while navigating after login

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#81]
Steps to reproduce::
1. Go to http://beta.utradea.com/
2. Login with your details
3. Now navigate to different menu in the profile page.
4. Observe the result  .
Note: The user gets logged out while navigating through the menu after login, Tested on Firefox, Chrome , Edge and on different systems

Actual result: User gets logged out after login and navigating through the different options
Expected result: User should not get logged out after login and navigating through the different options

Video : http://somup.com/creV2kDGH0

**Comment by zhan1634** [comment]
Utradea has been implementing a new authentication framework. This has now been fixed.
