### ISSUE TITLE
Login Page - Google's autogenerated password doesn't meet the capital/special char criteria and the browser doesn't remember the auto-generated password for the confirm password field

### ISSUE THREAD

**Issue by leiron-james** [Utradea-Inc/utradea-public#82]
Similar thought but would be nice to get the Google sign up / login button on the platform too along with Facebook.

![image](https://user-images.githubusercontent.com/78940042/109521920-ce8f5c80-7a7b-11eb-94a7-bce81a1e4534.png)

**Comment by zhan1634** [comment]
Google is coming in, from the back end everything is built we just need approval from Google - still waiting. 

In terms of confirm password - for signup we auto fill only fills one field by default, so you would need to confirm yourself.
