### ISSUE TITLE
Portfolio- All user Ideas- LogOut from site after click on own username.

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#83]
Reproduce Chrome, Firefox, Edge

Step of reproduce:
1. Log in website
2. Go to portfolio
3. go to ideas and click on any idea
4. click on own username

Actual result:
Logout

Expected result:
Redirect to portfolio

screencast:
https://screencast-o-matic.com/watch/creVFZWkGj

**Comment by nonameuser2019** [comment]
This is a critical bug

**Comment by zhan1634** [comment]
Utradea was implementing a new authentication framework, this has now been fixed.
