### ISSUE TITLE
Contact support option gets hidden after submitting the enquiry form . 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#84]
1. Go to https://beta.utradea.com/session/signin 
2. Login with your user-id and password
3. Go to profile tab and click on setting
4. Scroll down to contact support
5. Click on account inquiries  and select account inquiries 
6. Post your inquiries and click on submit
7. You won't see contact support option there anymore .

Actual result : Contact support option gets hidden after submitting the  inquiries  form . 
Expected result: User should see contact information after submitting the form .

For your reference please go through screen video  http://somup.com/crenj2DHEV

Tested on Chrome , Firefox, Edge

**Comment by zhan1634** [comment]
This is intentional to prevent users from spamming the content send button. One ticket is sufficient.
