### ISSUE TITLE
User is not able to select or copy contents from transaction , privacy policy, terms & condition , community guidelines

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#85]
1. Go to https://beta.utradea.com/session/signin
2. Login with your user-id and password
3. Go to profile tab and click on setting
4. Scroll down to Transactions
5. Try to copy record 
6. Observe the result.

Actual result: User is not able to copy any contents
Expected result : User should be able to copy contents

Screen video : http://somup.com/crenjUDHGe
Tested on Google chrome ,Firefox and edge

**Comment by zhan1634** [comment]
Resolved in latest update. Deploying at 12PM EST March 3rd, 2021.
