### ISSUE TITLE
User gets logged out when click on saved items filter 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#86]
1. Go to https://beta.utradea.com/session/signin.
2. Login with your user-id and password. 
3. Click on saved items.
4. Deselect all the filter items (ideas, news, sec filings).
5. Navigate to messenger menu and then again navigate over saved items.
6. Observe result.

Actual result: User gets logged out.
Expected result: User should not get logged out.

Screen Video : http://somup.com/crenIqDJXu
Note : Tested on Chrome Firefox and Edge . Cleared cache and cookies data.

**Comment by zhan1634** [comment]
Can you please check if this is still happening?

**Comment by Ashish8822** [comment]
> Can you please check if this is still happening?

Yes still happening

**Comment by zhan1634** [comment]
Messenger is inherently a different component. I've tried something, on the next update deploying tonight, can you please check to see if this reoccurs.

**Comment by Ashish8822** [comment]
> Messenger is inherently a different component. I've tried something, on the next update deploying tonight, can you please check to see if this reoccurs.

Yes sure

**Comment by Ashish8822** [comment]
Its still there again tested on Chrome Firefox and Edge

**Comment by zhan1634** [comment]
Can you video tape it again?

**Comment by zhan1634** [comment]
And this time can you open up the console, I want to see the network and console results. I see your video and I believe you and this is a critical bug, but I cannot reproduce it on my end by any means.

**Comment by Ashish8822** [comment]
> And this time can you open up the console, I want to see the network and console results. I see your video and I believe you and this is a critical bug, but I cannot reproduce it on my end by any means.

I have recorded again with console and network please check and confirm http://somup.com/cre16jDPDM
