### ISSUE TITLE
Page unresponsive 

### ISSUE THREAD

**Issue by vicxnguyen** [Utradea-Inc/utradea-public#87]
<img width="1440" alt="Screen Shot 2021-03-02 at 11 10 08 PM" src="https://user-images.githubusercontent.com/50087329/109751816-41e4bb80-7bad-11eb-8ea7-0b97161b9cd4.png">

Cannot click on anything beyond timeframe. Page freezes (cannot click back or on the home screen).

**Comment by zhan1634** [comment]
Resolved in latest update. Deploying at 12PM EST March 3rd, 2021.
