### ISSUE TITLE
Golden Watchlist UI bug 

### ISSUE THREAD

**Issue by vicxnguyen** [Utradea-Inc/utradea-public#88]
<img width="640" alt="Screen Shot 2021-03-02 at 11 37 07 PM" src="https://user-images.githubusercontent.com/50087329/109753451-46f73a00-7bb0-11eb-89e9-58edb3107f39.png">

yellow ring around the icons are not consistently circular

**Comment by zhan1634** [comment]
Resolved in next update to beta
