### ISSUE TITLE
Website gets unresponsive after clicking on timeframe option under post an idea section

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#89]
Steps to reproduce :
1. Go to https://beta.utradea.com.
2. Login with your credentials.
3. Go to post an idea section.
4. Select any ticker.
5. Enter details  and at the 4th stage ("Position and metrics") select any time frame
6. Observe the result

For reference please go through screen recording below
Video : http://somup.com/creei4DKDT
Note: Tested on Chrome , Firefox,  Edge and cleared cache and cookies data

**Comment by zhan1634** [comment]
Resolved in latest update. Deploying at 12PM EST March 3rd, 2021.
