### ISSUE TITLE
User is able to send blank inquiries in contact support

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#90]
1. Go to https://beta.utradea.com/session/signin
2.  Login with your credentials.
3. Navigate over profile and click on settings
4. Inside setting scroll down to Contact support.
5. Don't add any inquiry and click on submit
6. Observe

Screen recording : http://somup.com/creeQnDK0t

**Comment by zhan1634** [comment]
Resolved in latest update. Deploying at 12PM EST March 3rd, 2021.
