### ISSUE TITLE
list items overlap in contact support in mobile

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#91]
1. Go to https://beta.utradea.com
2. Enter your credentials and login.
3. Click on more 
4. Click on setting
5. Under setting scroll down to contact support.
6. Select the drop down list item and scroll up 
7. Observe
Note: When touched on drop-down item box in contact support the list open up and if you scroll up the list should be closed but instead it overlap on different boxes .

Screen recording : https://screencast-o-matic.com/watch/creeX4WKA6

** Tested on Mobile **

**Comment by zhan1634** [comment]
Should be resolved in the next update.
