### ISSUE TITLE
Refreshing Signup page redirects to the SignIn Page.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#92]
STR: 
1. Hit the URL.
2. Click on Signup button.
3. Refresh the page.
4. Observe the result.

Expected Result: It should stay on the Signup message not on the Sign In page.

Actual Result: It redirects me to the sign in page.

Refer Screencast: http://somup.com/creebXD7rS

**Comment by zhan1634** [comment]
Resolved in the latest update released to BETA on March 4, 11:59PM.
