### ISSUE TITLE
Saved ideas are not updating correctly in saved tab.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#93]
STR: 
1. Login with the credentials.
2. Save ideas from feed.
3. Navigate to saved tab
4. Check all the saved ideas are reflecting or not.

Screen record: http://somup.com/creebpD7OA

**Comment by zhan1634** [comment]
I cannot reproduce on my end unfortunately, can you try to reproduce again using a different browser and see if it's limited to ideas, or is it for news and sec as well.

**Comment by Ashish8822** [comment]
@zhan1634 Reproduced and seems like working fine but what would be the expected result when we click on `NEWS` and `SEC FILLINGS` ? I haven't seen any behavior after clicking on that button.

**Comment by zhan1634** [comment]
You haven't saved any news and sec filings correct? Go save some news and sec filings and observe the result. This main bug is closed.
