### ISSUE TITLE
Price since posted not reflecting the actual price since posted value. 

### ISSUE THREAD

**Issue by vicxnguyen** [Utradea-Inc/utradea-public#94]
<img width="1440" alt="Screen Shot 2021-03-03 at 9 54 58 PM" src="https://user-images.githubusercontent.com/50087329/109904427-3eb00500-7c6b-11eb-83c6-01c4e842fc6e.png">

I made a test position on ticker TIF - price entered was 131.46 during market closure. After posting the position, it says that I entered at 92.02 and thus falsely inflating my % change to 42.86% increase. I suspect this is the case for many of the other beta positions because they are up between 40-120% over a short period of time

**Comment by zhan1634** [comment]
This is not a bug, this is intentional. On all beta posts - depending on bearish or bullish, your position either gets added 40% on both target price and entry price or remove 40% so you can hit the target automatically.
