### ISSUE TITLE
Next button disappear in post and idea section

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#95]
Steps to Produce :  

1. Go to https://beta.utradea.com/session/signin
2. Login with your credentials
3. Navigate over Post and idea and click on it
4. Select any ticker click next and go to time frame section 
5. In the custom field click and enter any digit , you will see next button disappear and when you press back button still you wont be able to find next button . Even after refreshing the page next button did not appear.
6. Observe

For reference screen recording : http://somup.com/crefiRDs7C
Note : tested on Chrome, Firefox, Edge . Clear Cache and cookie data .

**Comment by zhan1634** [comment]
![image](https://user-images.githubusercontent.com/30502801/109976791-29b68e80-7cca-11eb-99f1-e3e8ce0b6609.png)

Please refer to the code. If you select a custom target price, it needs to be within the range.

**Comment by Ashish8822** [comment]
> ![image](https://user-images.githubusercontent.com/30502801/109976791-29b68e80-7cca-11eb-99f1-e3e8ce0b6609.png)
> 
> Please refer to the code. If you select a custom target price, it needs to be within the range.


Have you checked the video ?  refer to this   ""In the custom field click and enter any digit , you will see next button disappear and when you press **### back button still you wont be able to find next button** . Even after refreshing the page next button did not appear.""   Now suppose what you are referring  ""If you select a custom target price, it needs to be within the range."" is correct but what is the point that next button disappear ? Ok its acceptable that it won't allow me to go to next page that's why it is disabled , **### But IF I CLICK ON BACK BUTTON AND GO TO PREVIOUS PAGE STILL THE NEXT PAGE BUTTON IS NOT THERE ?? IS IT ACCEPTABLE ?? PLEASE HAVE A LOOK TO THE VIDEO**

**Comment by zhan1634** [comment]
Yes - okay you need to set a target price that's higher or lower. For example, if the price of the stock is at $10, and you are bullish (you think the price will go up), you can set a price of $10-$20. Any other price is invalid. For your video example, only a price from $17 - $34 is valid. Please let me know if that's not clear.

**Comment by Ashish8822** [comment]
> Yes - okay you need to set a target price that's higher or lower. For example, if the price of the stock is at $10, and you are bullish (you think the price will go up), you can set a price of $10-$20. Any other price is invalid. For your video example, only a price from $17 - $34 is valid. Please let me know if that's not clear.

Ok just one question why there is no next button appearing at this page in Ideas and catalyst ??
![image](https://user-images.githubusercontent.com/79117207/109995534-6323e400-7d34-11eb-8d98-cc8bf858621d.png)

**Also why no next button in Analysis type ?**
![image](https://user-images.githubusercontent.com/79117207/109995693-877fc080-7d34-11eb-8687-9f2e27b21dec.png)

**Comment by Ashish8822** [comment]
> > Yes - okay you need to set a target price that's higher or lower. For example, if the price of the stock is at $10, and you are bullish (you think the price will go up), you can set a price of $10-$20. Any other price is invalid. For your video example, only a price from $17 - $34 is valid. Please let me know if that's not clear.
> 
> Ok just one question why there is no next button appearing at this page in Ideas and catalyst ??
> ![image](https://user-images.githubusercontent.com/79117207/109995534-6323e400-7d34-11eb-8d98-cc8bf858621d.png)
> 
> **Also why no next button in Analysis type ?**
> ![image](https://user-images.githubusercontent.com/79117207/109995693-877fc080-7d34-11eb-8687-9f2e27b21dec.png)

Hii did you get this
