### ISSUE TITLE
0 digit does not go away even after clicking on the custom box in post an idea section

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#96]
When we click on post an idea and select any ticker and move towards Position Metrics section there is option to select custom price target when you click on custom price target box and try to type any digit lets suppose 17.91 the 0 digit does not disappear and its shows 017.91 . 

Steps :
1. Go to https://beta.utradea.com/
2. Login with your credentials
3. Navigate to post an idea section and select any ticker enter details and go to Position Metrics section
4. Click on custom price target  and enter any digit 
5. Observe.
 
Screen recording  :  http://somup.com/crefjQDsst
Note : Tested on Chrome , Firefox , Edge . Cookies and Cache clear

**Comment by zhan1634** [comment]
Resolved in the latest update released to BETA on March 4, 11:59PM.
