### ISSUE TITLE
Any thing written in General appears to be in fundamental and technical section also 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#97]
Steps : 
1. Go to https://beta.utradea.com/
2. Login with your credentials
3. Navigate to post an idea section and select any ticker
4. Select General and add any idea inside it 
5. Go back and open fundamental
6. Observe.

Screen recording: http://somup.com/crefj3DsMU
Note : Tested on Chrome , Firefox , Edge . Cookies and Cache clear

**Comment by zhan1634** [comment]
Resolved in the latest update released to BETA on March 4, 11:59PM.
