### ISSUE TITLE
Incorrect word  mistake in Post an Idea section 

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#99]
![image](https://user-images.githubusercontent.com/79117207/109934836-f2a8a300-7cf2-11eb-8872-70246524744b.png)

Incorrect word  in the sentence "Congratulations your ready to post!"   Instead of Your it should be You are . Please refer to screenshot .

**Comment by zhan1634** [comment]
GRAMMMMAAAAARRRRRRRR - fixed.
